cmake_minimum_required(VERSION 3.22)
project(material_model_consumer LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
find_package(lux-engine-editor-material-model REQUIRED COMPONENTS material_model)
add_executable(material_model_consumer main.cpp)
target_link_libraries(material_model_consumer PRIVATE lux::engine::editor::material_model)
if(MSVC)
    target_compile_options(material_model_consumer PRIVATE /UNDEBUG /Zc:__cplusplus /permissive- /utf-8)
else()
    target_compile_options(material_model_consumer PRIVATE -UNDEBUG)
endif()
enable_testing()
add_test(NAME material_model_consumer COMMAND material_model_consumer)
