if(LUX_EDITOR_BUILD_NATIVE_TESTS)
    add_executable(editor_scene_configuration scene_configuration.cpp)
    target_link_libraries(editor_scene_configuration PRIVATE scene_ui editor_extensions lux::engine::project::project_plugin_rendering lux::engine::scene::scene_asset)
    lux_editor_test_options(editor_scene_configuration)
    add_test(NAME editor.scene_configuration COMMAND editor_scene_configuration "${CMAKE_BINARY_DIR}")
    set_tests_properties(editor.scene_configuration PROPERTIES TIMEOUT 30 LABELS "editor;native")
endif()
