#pragma once
/**
 * @file ComponentTypeRegistry.hpp
 * @brief Runtime catalogue of ECS component types.
 *
 * This registry lives in `function::gameplay` deliberately: the notion of a
 * "component" is an ECS-layer concept, not a reflection-layer one.
 * `core::meta` knows how to describe arbitrary C++ types and surfaces their
 * class-level annotations, but it does not know what an entity is — the
 * `entt::registry` + `entt::entity` dependency is gameplay-side.
 *
 * The meta code generator detects the class-level annotation
 * `component=true` (emitted by the `LUX_COMPONENT()` macro) and writes a
 * registration block into the generated `.meta.cpp`. That block pushes a
 * `ComponentTypeEntry` into the singleton below, giving the Inspector +
 * Hierarchy panels a single fan-out point to discover every component type
 * available in the running editor.
 */

#include <lux/engine/function/visibility.h>

#include <entt/entt.hpp>

#include <span>
#include <string_view>
#include <vector>

namespace lux::meta { struct RefClass; }

namespace lux::gameplay
{
    /// Type-erased descriptor of an ECS component.
    ///
    /// Populated by code generated by the lux reflection toolchain for every
    /// class marked with `LUX_COMPONENT(...)`. Each entry carries the
    /// type-erased `has` / `get` shims that wrap `registry.all_of<T>` /
    /// `registry.try_get<T>` over a specific `T`, plus a back-pointer into
    /// the type's `lux::meta::RefClass` for field iteration.
    struct ComponentTypeEntry
    {
        /// Fully qualified type name. Points into a `static constexpr`
        /// string from the generated `.meta.cpp`; lifetime = process.
        std::string_view              full_name;

        /// Resolved by the generator at registration time. Non-null when
        /// reflection metadata survived to runtime. May be null on
        /// degenerate types — the Inspector falls back to a presence badge.
        const lux::meta::RefClass*    ref_class{ nullptr };

        /// `registry.all_of<T>(entity)`. Captureless-lambda decay; safe as
        /// a plain function pointer.
        bool   (*has)(entt::registry&, entt::entity){ nullptr };

        /// `registry.try_get<T>(entity)` as `void*`. The editor reads field
        /// values via offsets from this pointer; behaviour is undefined if
        /// `has` returned false.
        void*  (*get)(entt::registry&, entt::entity){ nullptr };

        /// `registry.emplace<T>(entity)` returning the new component as
        /// `void*`. The component is default-constructed; callers (the
        /// scene loader, future scripting "AddComponent" UI) then fill
        /// fields via the reflection layer. If the entity already has a
        /// `T`, behaviour is up to the shim — the generator emits one
        /// that uses `emplace_or_replace` so re-loading a scene is
        /// idempotent.
        void*  (*emplace)(entt::registry&, entt::entity){ nullptr };
    };

    /// Singleton catalogue of component types known to the running process.
    ///
    /// Lives in `function::gameplay` (a shared library), so every consumer
    /// that links it — the editor, gameplay-side tooling, future scripting
    /// front-ends — sees the same instance.
    class LUX_FUNCTION_PUBLIC ComponentTypeRegistry
    {
    public:
        static ComponentTypeRegistry& instance() noexcept;

        ComponentTypeRegistry(const ComponentTypeRegistry&)            = delete;
        ComponentTypeRegistry& operator=(const ComponentTypeRegistry&) = delete;

        /// Append @p entry to the catalogue. Idempotent against duplicate
        /// `full_name`s (later registrations replace earlier ones).
        void registerType(ComponentTypeEntry entry);

        /// Snapshot view of every entry. Iteration order = registration
        /// order. The returned span is invalidated by any subsequent
        /// `registerType`, so consumers should not cache it across frames.
        [[nodiscard]] std::span<const ComponentTypeEntry> all() const noexcept;

    private:
        ComponentTypeRegistry() = default;
        std::vector<ComponentTypeEntry> entries_;
    };

} // namespace lux::gameplay
