cmake_minimum_required(VERSION 3.22)
foreach(required SOURCE_DIR OUTPUT_ROOT PREFIX_PATH TOOLCHAIN_FILE)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
if(EXISTS "${OUTPUT_ROOT}/source")
    message(FATAL_ERROR "Use a fresh output root; existing source is never overwritten")
endif()
file(MAKE_DIRECTORY "${OUTPUT_ROOT}/source")
foreach(name CMakeLists.txt CounterAbility.hpp CounterAbility.cpp Behavior.hpp behavior.lua cpp.symbols.json
        lua.symbols.json GraphWriter.cpp main.cpp)
    file(COPY "${SOURCE_DIR}/${name}" DESTINATION "${OUTPUT_ROOT}/source")
endforeach()
set(source "${OUTPUT_ROOT}/source")
set(build "${OUTPUT_ROOT}/build")
set(dependency_options)
if(DEFINED DEPENDENCY_ROOT)
    list(APPEND dependency_options "-DVCPKG_INSTALLED_DIR=${DEPENDENCY_ROOT}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${build}" -G Ninja
    -DCMAKE_BUILD_TYPE=RelWithDebInfo "-DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}"
    "-DCMAKE_PREFIX_PATH=${PREFIX_PATH}" ${dependency_options}
    -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF RESULT_VARIABLE status
    OUTPUT_FILE "${OUTPUT_ROOT}/configure.log" ERROR_FILE "${OUTPUT_ROOT}/configure-error.log")
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Consumer configure failed (${status})")
endif()
function(build_and_run phase mode)
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${build}" --target all -j 4 -- -k 0
        RESULT_VARIABLE status OUTPUT_FILE "${OUTPUT_ROOT}/${phase}-build.log"
        ERROR_FILE "${OUTPUT_ROOT}/${phase}-build-error.log")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "${phase}: build failed (${status}); old executables are not run")
    endif()
    execute_process(COMMAND "${build}/lux_script_authoring_consumer.exe" "${mode}" "${OUTPUT_ROOT}/bindings.bin"
        RESULT_VARIABLE status OUTPUT_FILE "${OUTPUT_ROOT}/${phase}-run.log"
        ERROR_FILE "${OUTPUT_ROOT}/${phase}-run-error.log")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "${phase}: runtime failed (${status})")
    endif()
endfunction()
build_and_run(original save)
file(SHA256 "${OUTPUT_ROOT}/bindings.bin" binding_hash)
file(READ "${source}/Behavior.hpp" cpp)
string(REPLACE "void update(" "void renamedUpdate(" cpp "${cpp}")
string(REPLACE "Host.first" "Host.missing" cpp "${cpp}")
file(WRITE "${source}/Behavior.hpp" "${cpp}")
file(READ "${source}/behavior.lua" lua)
string(REPLACE "Common:update(" "Common:renamedUpdate(" lua "${lua}")
string(REPLACE "Host.first" "Host.missing" lua "${lua}")
file(WRITE "${source}/behavior.lua" "${lua}")
file(READ "${source}/lua.symbols.json" ledger)
string(REPLACE "Common:update" "Common:renamedUpdate" ledger "${ledger}")
file(WRITE "${source}/lua.symbols.json" "${ledger}")
file(READ "${source}/GraphWriter.cpp" graph)
string(REPLACE "\"observe\"" "\"renamed_observe\"" graph "${graph}")
string(REPLACE "Host.first" "Host.missing" graph "${graph}")
file(WRITE "${source}/GraphWriter.cpp" "${graph}")
build_and_run(renamed load)
string(REPLACE ", script_suggest_hook=\"Host.missing\"" "" cpp "${cpp}")
file(WRITE "${source}/Behavior.hpp" "${cpp}")
string(REPLACE "---@lux.suggest hook Host.missing\n" "" lua "${lua}")
file(WRITE "${source}/behavior.lua" "${lua}")
string(REPLACE "{{script::EScriptBindingHintKind::HOOK, \"Host.missing\"}}" "{}" graph "${graph}")
file(WRITE "${source}/GraphWriter.cpp" "${graph}")
build_and_run(no-defaults load)
string(REPLACE "std::int32_t input" "float input" cpp "${cpp}")
file(WRITE "${source}/Behavior.hpp" "${cpp}")
build_and_run(incompatible reject)
string(REPLACE "float input" "std::int32_t input" cpp "${cpp}")
file(WRITE "${source}/Behavior.hpp" "${cpp}")
file(SHA256 "${build}/lua.lxsa" old_lua_schema_artifact)
file(READ "${source}/CounterAbility.hpp" ability)
string(REPLACE "version=1" "version=2" ability "${ability}")
file(WRITE "${source}/CounterAbility.hpp" "${ability}")
build_and_run(schema-version load)
file(SHA256 "${build}/lua.lxsa" new_lua_schema_artifact)
if(new_lua_schema_artifact STREQUAL old_lua_schema_artifact)
    message(FATAL_ERROR "Canonical Ability schema change did not invalidate Lua packaging")
endif()
file(SHA256 "${OUTPUT_ROOT}/bindings.bin" final_binding_hash)
if(NOT final_binding_hash STREQUAL binding_hash)
    message(FATAL_ERROR "A source reimport rewrote the saved user selection")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${build}" --target all -j 4 -- -k 0
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${OUTPUT_ROOT}/second-build.log" "${output}\n${error}")
if(NOT status EQUAL 0 OR NOT output MATCHES "no work to do")
    message(FATAL_ERROR "Second consumer build is not a no-op")
endif()
message(STATUS "Three-language rename/default removal/schema reimport closure passed; bindings=${binding_hash}")
