foreach(required GENERATOR CONFIG IR TEMPLATES OUTPUT_ROOT FORMATTER STYLE)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing Inspector generation argument: ${required}")
    endif()
endforeach()
set(staging "${OUTPUT_ROOT}/staging")
file(REMOVE "${OUTPUT_ROOT}/inspector.complete")
execute_process(COMMAND "${GENERATOR}" "${CONFIG}" "${IR}" "${TEMPLATES}" "${staging}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Inspector semantic preparation or rendering failed (${result})")
endif()
file(READ "${staging}/outputs.json" manifest)
string(JSON count LENGTH "${manifest}")
math(EXPR last "${count} - 1")
foreach(index RANGE 0 ${last})
    string(JSON name GET "${manifest}" ${index})
    execute_process(COMMAND "${FORMATTER}" "--style=file:${STYLE}" -i "${staging}/${name}" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Inspector formatting failed (${result}): ${name}")
    endif()
endforeach()
# All semantic, template and formatter work succeeded before any published file changes.
# Ninja never treats a failed publication as a successful group; no cross-file atomicity is claimed.
foreach(index RANGE 0 ${last})
    string(JSON name GET "${manifest}" ${index})
    file(COPY_FILE "${staging}/${name}" "${OUTPUT_ROOT}/${name}" ONLY_IF_DIFFERENT)
endforeach()
file(WRITE "${OUTPUT_ROOT}/inspector.complete" "MetaUnit/inja generation complete\n")
