add_subdirectory(domain)
add_subdirectory(process)
if(LUX_BUILD_PROFILE MATCHES "^(EDITOR|TOOLCHAIN)$")
    add_subdirectory(authoring)
endif()
if(LUX_BUILD_PROFILE STREQUAL "EDITOR")
    add_subdirectory(editor)
elseif(LUX_BUILD_PROFILE STREQUAL "TOOLCHAIN")
    add_subdirectory(toolchain)
endif()
