include_guard(GLOBAL)

function(lux_cpp_static_scripts)
    set(one_value TARGET NAME SOURCE LOGICAL_PATH MODULE DESCRIPTOR OWNER SCOPE SYMBOL_LEDGER OUTPUT_ROOT)
    set(multi_value ABILITY_TYPES ABILITY_HEADERS EVENT_SOURCES DEPENDS EXTRA_COMPILE_OPTIONS)
    cmake_parse_arguments(ARGS "" "${one_value}" "${multi_value}" ${ARGN})
    foreach(required TARGET NAME SOURCE LOGICAL_PATH MODULE DESCRIPTOR SCOPE SYMBOL_LEDGER)
        if(NOT ARGS_${required})
            message(FATAL_ERROR "[lux_cpp_static_scripts] ${required} is required")
        endif()
    endforeach()
    if(NOT TARGET ${ARGS_TARGET} OR NOT ARGS_NAME MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
        message(FATAL_ERROR "[lux_cpp_static_scripts] invalid target or generated declaration name")
    endif()
    if(NOT ARGS_SCOPE MATCHES "^(ENTITY|SIMULATION)$")
        message(FATAL_ERROR "[lux_cpp_static_scripts] SCOPE must be ENTITY or SIMULATION")
    endif()
    if(ARGS_SCOPE STREQUAL "ENTITY" AND NOT ARGS_OWNER)
        message(FATAL_ERROR "[lux_cpp_static_scripts] entity scripts require an explicit object declaration")
    endif()
    if(NOT COMMAND lux_add_codegen_job)
        find_package(lux-cxx REQUIRED CONFIG COMPONENTS reflection_generator)
        include_component_cmake_scripts(lux::cxx::reflection_generator)
    endif()
    get_filename_component(source "${ARGS_SOURCE}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    get_filename_component(source_directory "${source}" DIRECTORY)
    target_include_directories(${ARGS_TARGET} PRIVATE "${source_directory}")
    get_filename_component(ledger "${ARGS_SYMBOL_LEDGER}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ledger}")
    file(READ "${ledger}" ledger_json)
    string(JSON ledger_schema GET "${ledger_json}" schema)
    string(JSON ledger_version GET "${ledger_json}" version)
    if(NOT ledger_schema STREQUAL "lux-script-symbol-ledger" OR NOT ledger_version EQUAL 1)
        message(FATAL_ERROR "[lux_cpp_static_scripts] unsupported symbol ledger")
    endif()
    set(symbols "{}")
    set(seen_symbols)
    string(JSON count LENGTH "${ledger_json}" entries)
    if(count LESS 1)
        message(FATAL_ERROR "[lux_cpp_static_scripts] empty symbol ledger")
    endif()
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
        string(JSON key GET "${ledger_json}" entries ${index} source_identity)
        string(JSON symbol GET "${ledger_json}" entries ${index} symbol)
        string(LENGTH "${symbol}" symbol_length)
        string(JSON previous ERROR_VARIABLE absent GET "${symbols}" "${key}")
        if(NOT absent OR key STREQUAL "" OR NOT symbol MATCHES "^[1-9][0-9]*$" OR symbol IN_LIST seen_symbols OR
            symbol_length GREATER 20 OR (symbol_length EQUAL 20 AND symbol STRGREATER "18446744073709551615"))
            message(FATAL_ERROR "[lux_cpp_static_scripts] duplicate/invalid ledger entry '${key}'")
        endif()
        list(APPEND seen_symbols "${symbol}")
        string(JSON symbols SET "${symbols}" "${key}" "${symbol}")
    endforeach()
    set(config "{}")
    foreach(field NAME MODULE DESCRIPTOR OWNER SCOPE)
        string(TOLOWER "${field}" json_key)
        _meta_json_escape(escaped "${ARGS_${field}}")
        string(JSON config SET "${config}" "${json_key}" "\"${escaped}\"")
    endforeach()
    string(JSON config SET "${config}" symbols "${symbols}")
    foreach(field ABILITY_TYPES ABILITY_HEADERS EVENT_SOURCES)
        set(array "[]")
        set(index 0)
        foreach(value IN LISTS ARGS_${field})
            _meta_json_escape(escaped "${value}")
            string(JSON array SET "${array}" ${index} "\"${escaped}\"")
            math(EXPR index "${index} + 1")
        endforeach()
        string(TOLOWER "${field}" json_key)
        string(JSON config SET "${config}" "${json_key}" "${array}")
    endforeach()
    if(ARGS_OUTPUT_ROOT)
        set(output "${ARGS_OUTPUT_ROOT}")
    else()
        set(output "${CMAKE_CURRENT_BINARY_DIR}/generated/${ARGS_TARGET}/cpp_scripts/${ARGS_NAME}")
    endif()
    if(EXISTS "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/template/cpp_static_script.template")
        set(templates "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/template")
    else()
        get_filename_component(package "${CMAKE_CURRENT_FUNCTION_LIST_DIR}" DIRECTORY)
        set(templates "${package}/template")
    endif()
    # Repeated projections of one header in one target share one parse/environment.
    # This build-local key is never an artifact identity or ScriptSymbolId.
    string(SHA256 parse_key "${ARGS_TARGET}|${source}|${ARGS_LOGICAL_PATH}|${ARGS_EXTRA_COMPILE_OPTIONS}")
    string(SUBSTRING "${parse_key}" 0 16 parse_key)
    set(job "${ARGS_TARGET}_cpp_script_${parse_key}")
    if(NOT TARGET ${job})
        lux_add_codegen_job(NAME ${job} MARKER luxref TARGET_FILES "${source}" LOGICAL_PATHS "${ARGS_LOGICAL_PATH}"
            EXTRA_COMPILE_OPTIONS -D__LUX_PARSE_TIME__=1 ${ARGS_EXTRA_COMPILE_OPTIONS})
        cmake_language(EVAL CODE
            "cmake_language(DEFER CALL lux_target_add_codegen TARGET \"${ARGS_TARGET}\" JOB \"${job}\")")
    endif()
    set_property(TARGET ${job} APPEND PROPERTY LUX_CODEGEN_DEPENDS "${ledger}" ${ARGS_DEPENDS})
    lux_codegen_add_validation(JOB ${job} NAME ${ARGS_NAME}_contract_validation
        TEMPLATE "${templates}/cpp_static_script.validation.template" JSON_FIELD "{\"script\":${config}}")
    lux_codegen_add_projection(JOB ${job} NAME ${ARGS_NAME}_declaration TEMPLATE "${templates}/cpp_static_script_header.template"
        OUTPUT_ROOT "${output}" OUTPUT_SUFFIX .${ARGS_NAME}.script.generated.hpp JSON_FIELD "{\"script\":${config}}" FLAT_OUTPUT)
    lux_codegen_add_projection(JOB ${job} NAME ${ARGS_NAME}_executable TEMPLATE "${templates}/cpp_static_script.template"
        OUTPUT_ROOT "${output}" OUTPUT_SUFFIX .${ARGS_NAME}.script.generated.cpp JSON_FIELD "{\"script\":${config}}" FLAT_OUTPUT)
    set_property(TARGET ${ARGS_TARGET} APPEND PROPERTY LUX_CPP_STATIC_SCRIPT_JOBS ${job})
endfunction()
