foreach(required GENERATOR CONFIG TEMPLATES OUTPUT_ROOT NAME)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Module generation requires ${required}")
    endif()
endforeach()
set(staging "${OUTPUT_ROOT}/staging")
execute_process(COMMAND "${GENERATOR}" "${CONFIG}" "${TEMPLATES}" "${staging}"
    RESULT_VARIABLE result COMMAND_ECHO STDOUT)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Module semantic/template generation failed: ${result}")
endif()
foreach(suffix modules.hpp modules.cpp)
    configure_file("${staging}/${NAME}.${suffix}" "${OUTPUT_ROOT}/${NAME}.${suffix}" COPYONLY)
endforeach()
file(WRITE "${OUTPUT_ROOT}/modules.complete" "MetaUnit/inja module index complete\n")
