#include <lux/engine/editor/FrameworkErrors.hpp>
#include <lux/engine/error/ErrorRegistry.hpp>

namespace lux::editor
{
    FrameworkResult<void> registerFrameworkErrors() noexcept
    {
        static constexpr error::ErrorDescriptor descriptors[]{
            {"lux.ui.render_configuration",
             "UI render configuration code {0}",
             error::ERecovery::PERMANENT,
             {error::EArgument::UNSIGNED}},
            {"lux.editor.window_has_no_native_output", "Window has no native output", error::ERecovery::PERMANENT},
            {"lux.editor.native_ui_output_is_not_implemented_on_this_platform",
             "Native UI output is not implemented on this platform",
             error::ERecovery::PERMANENT},
            {"lux.editor.project_change_inside_a_host_operation",
             "Project change inside a host operation",
             error::ERecovery::RETRYABLE},
            {"lux.editor.invalid_layout_item", "Invalid layout item", error::ERecovery::PERMANENT},
            {"lux.editor.duplicate_ui_instance_name", "Duplicate UI instance name", error::ERecovery::PERMANENT},
            {"lux.editor.ui_factory_returned_an_attached_or_null_pane",
             "UI factory returned an attached or null Pane",
             error::ERecovery::PERMANENT},
            {"lux.editor.cannot_mount_project_windows",
             "Cannot mount project windows: code {0}",
             error::ERecovery::PERMANENT,
             {error::EArgument::UNSIGNED}},
            {"lux.editor.recursive_host_frame", "Recursive host frame", error::ERecovery::RETRYABLE},
            {"lux.ui.capture", "UI capture code {0}", error::ERecovery::PERMANENT, {error::EArgument::UNSIGNED}},
            {"lux.editor.invalid_window_extent", "Invalid window extent", error::ERecovery::PERMANENT},
            {"lux.editor.editor_requires_object_thread", "Editor requires object thread", error::ERecovery::BUG},
            {"lux.editor.project_needs_a_name_and_absolute_root",
             "Project needs a name and absolute root",
             error::ERecovery::PERMANENT},
            {"lux.editor.service_registration_is_frozen", "Service registration is frozen", error::ERecovery::PERMANENT
            },
            {"lux.editor.duplicate_service_type", "Duplicate service type", error::ERecovery::PERMANENT},
            {"lux.editor.service_use_outside_project_lifetime",
             "Service use outside project lifetime",
             error::ERecovery::PERMANENT},
            {"lux.editor.service_type_is_not_registered", "Service type is not registered", error::ERecovery::PERMANENT
            },
            {"lux.editor.recursive_service_factory", "Recursive service factory", error::ERecovery::PERMANENT},
            {"lux.editor.ui_registration_is_frozen", "UI registration is frozen", error::ERecovery::PERMANENT},
            {"lux.editor.invalid_ui_factory", "Invalid UI factory", error::ERecovery::PERMANENT},
            {"lux.editor.duplicate_ui_type", "Duplicate UI type", error::ERecovery::PERMANENT},
            {"lux.editor.ui_registration_is_not_frozen", "UI registration is not frozen", error::ERecovery::PERMANENT},
            {"lux.editor.unknown_ui_type", "Unknown UI type", error::ERecovery::PERMANENT},
            {"lux.editor.project_services_require_owner_thread",
             "Project services require owner thread",
             error::ERecovery::BUG},
            {"lux.editor.empty_service_factory", "Empty service factory", error::ERecovery::PERMANENT},
            {"lux.editor.null_service", "Null service", error::ERecovery::PERMANENT},
            {"lux.editor.scene_tool_registration_is_frozen",
             "Scene tool registration is frozen",
             error::ERecovery::PERMANENT},
            {"lux.editor.invalid_scene_tool_factory", "Invalid scene tool factory", error::ERecovery::PERMANENT},
            {"lux.editor.duplicate_scene_tool_rule", "Duplicate scene tool rule", error::ERecovery::PERMANENT},
            {"lux.editor.null_scene_tool_set", "Null scene tool set", error::ERecovery::PERMANENT},
            {"lux.editor.scene_tool_registration_is_not_frozen",
             "Scene tool registration is not frozen",
             error::ERecovery::PERMANENT},
            {"lux.editor.ambiguous_scene_tool_rules", "Ambiguous scene tool rules", error::ERecovery::PERMANENT},
            {"lux.editor.no_matching_scene_tool_rule", "No matching scene tool rule", error::ERecovery::PERMANENT},
            {"lux.scene.description",
             "Scene description code {0}, system {1}, subject {2}",
             error::ERecovery::NEEDS_INPUT,
             {error::EArgument::UNSIGNED, error::EArgument::UNSIGNED, error::EArgument::HEX}},
            {"lux.ui.configuration_encode",
             "UI configuration encoding code {0}, offset {1}",
             error::ERecovery::NEEDS_INPUT,
             {error::EArgument::UNSIGNED, error::EArgument::UNSIGNED}},
            {"lux.editor.glfw_initialization_failed", "GLFW initialization failed", error::ERecovery::PERMANENT},
            {"lux.editor.native_window_creation_failed",
             "Native window creation failed: code {0}",
             error::ERecovery::PERMANENT,
             {error::EArgument::UNSIGNED}},
            {"lux.editor.root_initialization_failed",
             "Root initialization failed: code {0}",
             error::ERecovery::PERMANENT,
             {error::EArgument::UNSIGNED}},
            {"lux.editor.native_input_delivery_failed",
             "Native input delivery failed: code {0}",
             error::ERecovery::PERMANENT,
             {error::EArgument::UNSIGNED}},
            {"lux.process.execution.0",
             "ExecutionRuntime code {0}",
             error::ERecovery::PERMANENT,
             {error::EArgument::UNSIGNED}},
            {"lux.process.execution.1",
             "ExecutionRuntime code {0}",
             error::ERecovery::PERMANENT,
             {error::EArgument::UNSIGNED}},
            {"lux.process.execution.2",
             "ExecutionRuntime code {0}",
             error::ERecovery::RETRYABLE,
             {error::EArgument::UNSIGNED}},
            {"lux.process.execution.3",
             "ExecutionRuntime code {0}",
             error::ERecovery::PERMANENT,
             {error::EArgument::UNSIGNED}},
            {"lux.process.execution.4",
             "ExecutionRuntime code {0}",
             error::ERecovery::PERMANENT,
             {error::EArgument::UNSIGNED}},
            {"lux.process.execution.5",
             "ExecutionRuntime code {0}",
             error::ERecovery::PERMANENT,
             {error::EArgument::UNSIGNED}},
            {"lux.process.execution.6",
             "ExecutionRuntime code {0}",
             error::ERecovery::PERMANENT,
             {error::EArgument::UNSIGNED}},
            {"lux.process.execution.7",
             "ExecutionRuntime code {0}",
             error::ERecovery::PERMANENT,
             {error::EArgument::UNSIGNED}},
            {"lux.process.execution.8",
             "ExecutionRuntime code {0}",
             error::ERecovery::RETRYABLE,
             {error::EArgument::UNSIGNED}},
            {"lux.process.execution.9",
             "ExecutionRuntime code {0}",
             error::ERecovery::PERMANENT,
             {error::EArgument::UNSIGNED}},
            {"lux.process.execution.10",
             "ExecutionRuntime code {0}",
             error::ERecovery::PERMANENT,
             {error::EArgument::UNSIGNED}},
            {"lux.process.execution.unknown",
             "ExecutionRuntime code {0}",
             error::ERecovery::BUG,
             {error::EArgument::UNSIGNED}},
            {"lux.editor.ui_clear_busy",
             "Cannot clear project windows: UI code {0}",
             error::ERecovery::RETRYABLE,
             {error::EArgument::UNSIGNED}},
            {"lux.editor.ui_clear",
             "Cannot clear project windows: UI code {0}",
             error::ERecovery::PERMANENT,
             {error::EArgument::UNSIGNED}}
        };
        static const auto registered = error::ErrorRegistry::instance().registerTypes(descriptors);
        return registered;
    }
} // namespace lux::editor
