cmake_minimum_required(VERSION 3.22)
project(lux_render_client_consumer LANGUAGES CXX)
find_package(lux-engine-function REQUIRED COMPONENTS render_client)
add_executable(lux_render_client_consumer main.cpp)
target_compile_features(lux_render_client_consumer PRIVATE cxx_std_20)
target_link_libraries(lux_render_client_consumer PRIVATE lux::engine::function::render_client)
