#pragma once

#include <lux/engine/description/Image.hpp>
#include <vulkan/vulkan.h>

namespace lux::render::vulkan
{
    // Native translation of the one neutral format authority; no numeric-enum correspondence.
    [[nodiscard]] constexpr VkFormat nativeTextureFormat(rdesc::ETextureFormat format) noexcept
    {
        switch (format)
        {
        case rdesc::ETextureFormat::R8_UNORM:
            return VK_FORMAT_R8_UNORM;
        case rdesc::ETextureFormat::R8_SNORM:
            return VK_FORMAT_R8_SNORM;
        case rdesc::ETextureFormat::R8_UINT:
            return VK_FORMAT_R8_UINT;
        case rdesc::ETextureFormat::R8_SINT:
            return VK_FORMAT_R8_SINT;
        case rdesc::ETextureFormat::R8_SRGB:
            return VK_FORMAT_R8_SRGB;
        case rdesc::ETextureFormat::R16_UNORM:
            return VK_FORMAT_R16_UNORM;
        case rdesc::ETextureFormat::R16_SNORM:
            return VK_FORMAT_R16_SNORM;
        case rdesc::ETextureFormat::R16_UINT:
            return VK_FORMAT_R16_UINT;
        case rdesc::ETextureFormat::R16_SINT:
            return VK_FORMAT_R16_SINT;
        case rdesc::ETextureFormat::R16_SFLOAT:
            return VK_FORMAT_R16_SFLOAT;
        case rdesc::ETextureFormat::R32_UINT:
            return VK_FORMAT_R32_UINT;
        case rdesc::ETextureFormat::R32_SINT:
            return VK_FORMAT_R32_SINT;
        case rdesc::ETextureFormat::R32_SFLOAT:
            return VK_FORMAT_R32_SFLOAT;
        case rdesc::ETextureFormat::RG8_UNORM:
            return VK_FORMAT_R8G8_UNORM;
        case rdesc::ETextureFormat::RG8_SNORM:
            return VK_FORMAT_R8G8_SNORM;
        case rdesc::ETextureFormat::RG8_UINT:
            return VK_FORMAT_R8G8_UINT;
        case rdesc::ETextureFormat::RG8_SINT:
            return VK_FORMAT_R8G8_SINT;
        case rdesc::ETextureFormat::RG8_SRGB:
            return VK_FORMAT_R8G8_SRGB;
        case rdesc::ETextureFormat::RG16_UNORM:
            return VK_FORMAT_R16G16_UNORM;
        case rdesc::ETextureFormat::RG16_SNORM:
            return VK_FORMAT_R16G16_SNORM;
        case rdesc::ETextureFormat::RG16_UINT:
            return VK_FORMAT_R16G16_UINT;
        case rdesc::ETextureFormat::RG16_SINT:
            return VK_FORMAT_R16G16_SINT;
        case rdesc::ETextureFormat::RG16_SFLOAT:
            return VK_FORMAT_R16G16_SFLOAT;
        case rdesc::ETextureFormat::RG32_UINT:
            return VK_FORMAT_R32G32_UINT;
        case rdesc::ETextureFormat::RG32_SINT:
            return VK_FORMAT_R32G32_SINT;
        case rdesc::ETextureFormat::RG32_SFLOAT:
            return VK_FORMAT_R32G32_SFLOAT;
        case rdesc::ETextureFormat::RGB8_UNORM:
            return VK_FORMAT_R8G8B8_UNORM;
        case rdesc::ETextureFormat::RGB8_SNORM:
            return VK_FORMAT_R8G8B8_SNORM;
        case rdesc::ETextureFormat::RGB8_UINT:
            return VK_FORMAT_R8G8B8_UINT;
        case rdesc::ETextureFormat::RGB8_SINT:
            return VK_FORMAT_R8G8B8_SINT;
        case rdesc::ETextureFormat::RGB8_SRGB:
            return VK_FORMAT_R8G8B8_SRGB;
        case rdesc::ETextureFormat::RGB32_UINT:
            return VK_FORMAT_R32G32B32_UINT;
        case rdesc::ETextureFormat::RGB32_SINT:
            return VK_FORMAT_R32G32B32_SINT;
        case rdesc::ETextureFormat::RGB32_SFLOAT:
            return VK_FORMAT_R32G32B32_SFLOAT;
        case rdesc::ETextureFormat::RGBA8_UNORM:
            return VK_FORMAT_R8G8B8A8_UNORM;
        case rdesc::ETextureFormat::RGBA8_SNORM:
            return VK_FORMAT_R8G8B8A8_SNORM;
        case rdesc::ETextureFormat::RGBA8_UINT:
            return VK_FORMAT_R8G8B8A8_UINT;
        case rdesc::ETextureFormat::RGBA8_SINT:
            return VK_FORMAT_R8G8B8A8_SINT;
        case rdesc::ETextureFormat::RGBA8_SRGB:
            return VK_FORMAT_R8G8B8A8_SRGB;
        case rdesc::ETextureFormat::RGBA16_UNORM:
            return VK_FORMAT_R16G16B16A16_UNORM;
        case rdesc::ETextureFormat::RGBA16_SNORM:
            return VK_FORMAT_R16G16B16A16_SNORM;
        case rdesc::ETextureFormat::RGBA16_UINT:
            return VK_FORMAT_R16G16B16A16_UINT;
        case rdesc::ETextureFormat::RGBA16_SINT:
            return VK_FORMAT_R16G16B16A16_SINT;
        case rdesc::ETextureFormat::RGBA16_SFLOAT:
            return VK_FORMAT_R16G16B16A16_SFLOAT;
        case rdesc::ETextureFormat::RGBA32_UINT:
            return VK_FORMAT_R32G32B32A32_UINT;
        case rdesc::ETextureFormat::RGBA32_SINT:
            return VK_FORMAT_R32G32B32A32_SINT;
        case rdesc::ETextureFormat::RGBA32_SFLOAT:
            return VK_FORMAT_R32G32B32A32_SFLOAT;
        case rdesc::ETextureFormat::BGRA8_UNORM:
            return VK_FORMAT_B8G8R8A8_UNORM;
        case rdesc::ETextureFormat::BGRA8_SRGB:
            return VK_FORMAT_B8G8R8A8_SRGB;
        case rdesc::ETextureFormat::D16_UNORM:
            return VK_FORMAT_D16_UNORM;
        case rdesc::ETextureFormat::D32_SFLOAT:
            return VK_FORMAT_D32_SFLOAT;
        case rdesc::ETextureFormat::D16_UNORM_S8_UINT:
            return VK_FORMAT_D16_UNORM_S8_UINT;
        case rdesc::ETextureFormat::D24_UNORM_S8_UINT:
            return VK_FORMAT_D24_UNORM_S8_UINT;
        case rdesc::ETextureFormat::D32_SFLOAT_S8_UINT:
            return VK_FORMAT_D32_SFLOAT_S8_UINT;
        case rdesc::ETextureFormat::BC1_RGB_UNORM:
            return VK_FORMAT_BC1_RGB_UNORM_BLOCK;
        case rdesc::ETextureFormat::BC1_RGB_SRGB:
            return VK_FORMAT_BC1_RGB_SRGB_BLOCK;
        case rdesc::ETextureFormat::BC1_RGBA_UNORM:
            return VK_FORMAT_BC1_RGBA_UNORM_BLOCK;
        case rdesc::ETextureFormat::BC1_RGBA_SRGB:
            return VK_FORMAT_BC1_RGBA_SRGB_BLOCK;
        case rdesc::ETextureFormat::BC2_UNORM:
            return VK_FORMAT_BC2_UNORM_BLOCK;
        case rdesc::ETextureFormat::BC2_SRGB:
            return VK_FORMAT_BC2_SRGB_BLOCK;
        case rdesc::ETextureFormat::BC3_UNORM:
            return VK_FORMAT_BC3_UNORM_BLOCK;
        case rdesc::ETextureFormat::BC3_SRGB:
            return VK_FORMAT_BC3_SRGB_BLOCK;
        case rdesc::ETextureFormat::BC4_UNORM:
            return VK_FORMAT_BC4_UNORM_BLOCK;
        case rdesc::ETextureFormat::BC4_SNORM:
            return VK_FORMAT_BC4_SNORM_BLOCK;
        case rdesc::ETextureFormat::BC5_UNORM:
            return VK_FORMAT_BC5_UNORM_BLOCK;
        case rdesc::ETextureFormat::BC5_SNORM:
            return VK_FORMAT_BC5_SNORM_BLOCK;
        case rdesc::ETextureFormat::BC6H_UFLOAT:
            return VK_FORMAT_BC6H_UFLOAT_BLOCK;
        case rdesc::ETextureFormat::BC6H_SFLOAT:
            return VK_FORMAT_BC6H_SFLOAT_BLOCK;
        case rdesc::ETextureFormat::BC7_UNORM:
            return VK_FORMAT_BC7_UNORM_BLOCK;
        case rdesc::ETextureFormat::BC7_SRGB:
            return VK_FORMAT_BC7_SRGB_BLOCK;
        default:
            return VK_FORMAT_UNDEFINED;
        }
    }

    [[nodiscard]] constexpr rdesc::ETextureFormat neutralTextureFormat(VkFormat format) noexcept
    {
        switch (format)
        {
        case VK_FORMAT_R8_UNORM:
            return rdesc::ETextureFormat::R8_UNORM;
        case VK_FORMAT_R8_SNORM:
            return rdesc::ETextureFormat::R8_SNORM;
        case VK_FORMAT_R8_UINT:
            return rdesc::ETextureFormat::R8_UINT;
        case VK_FORMAT_R8_SINT:
            return rdesc::ETextureFormat::R8_SINT;
        case VK_FORMAT_R8_SRGB:
            return rdesc::ETextureFormat::R8_SRGB;
        case VK_FORMAT_R16_UNORM:
            return rdesc::ETextureFormat::R16_UNORM;
        case VK_FORMAT_R16_SNORM:
            return rdesc::ETextureFormat::R16_SNORM;
        case VK_FORMAT_R16_UINT:
            return rdesc::ETextureFormat::R16_UINT;
        case VK_FORMAT_R16_SINT:
            return rdesc::ETextureFormat::R16_SINT;
        case VK_FORMAT_R16_SFLOAT:
            return rdesc::ETextureFormat::R16_SFLOAT;
        case VK_FORMAT_R32_UINT:
            return rdesc::ETextureFormat::R32_UINT;
        case VK_FORMAT_R32_SINT:
            return rdesc::ETextureFormat::R32_SINT;
        case VK_FORMAT_R32_SFLOAT:
            return rdesc::ETextureFormat::R32_SFLOAT;
        case VK_FORMAT_R8G8_UNORM:
            return rdesc::ETextureFormat::RG8_UNORM;
        case VK_FORMAT_R8G8_SNORM:
            return rdesc::ETextureFormat::RG8_SNORM;
        case VK_FORMAT_R8G8_UINT:
            return rdesc::ETextureFormat::RG8_UINT;
        case VK_FORMAT_R8G8_SINT:
            return rdesc::ETextureFormat::RG8_SINT;
        case VK_FORMAT_R8G8_SRGB:
            return rdesc::ETextureFormat::RG8_SRGB;
        case VK_FORMAT_R16G16_UNORM:
            return rdesc::ETextureFormat::RG16_UNORM;
        case VK_FORMAT_R16G16_SNORM:
            return rdesc::ETextureFormat::RG16_SNORM;
        case VK_FORMAT_R16G16_UINT:
            return rdesc::ETextureFormat::RG16_UINT;
        case VK_FORMAT_R16G16_SINT:
            return rdesc::ETextureFormat::RG16_SINT;
        case VK_FORMAT_R16G16_SFLOAT:
            return rdesc::ETextureFormat::RG16_SFLOAT;
        case VK_FORMAT_R32G32_UINT:
            return rdesc::ETextureFormat::RG32_UINT;
        case VK_FORMAT_R32G32_SINT:
            return rdesc::ETextureFormat::RG32_SINT;
        case VK_FORMAT_R32G32_SFLOAT:
            return rdesc::ETextureFormat::RG32_SFLOAT;
        case VK_FORMAT_R8G8B8_UNORM:
            return rdesc::ETextureFormat::RGB8_UNORM;
        case VK_FORMAT_R8G8B8_SNORM:
            return rdesc::ETextureFormat::RGB8_SNORM;
        case VK_FORMAT_R8G8B8_UINT:
            return rdesc::ETextureFormat::RGB8_UINT;
        case VK_FORMAT_R8G8B8_SINT:
            return rdesc::ETextureFormat::RGB8_SINT;
        case VK_FORMAT_R8G8B8_SRGB:
            return rdesc::ETextureFormat::RGB8_SRGB;
        case VK_FORMAT_R32G32B32_UINT:
            return rdesc::ETextureFormat::RGB32_UINT;
        case VK_FORMAT_R32G32B32_SINT:
            return rdesc::ETextureFormat::RGB32_SINT;
        case VK_FORMAT_R32G32B32_SFLOAT:
            return rdesc::ETextureFormat::RGB32_SFLOAT;
        case VK_FORMAT_R8G8B8A8_UNORM:
            return rdesc::ETextureFormat::RGBA8_UNORM;
        case VK_FORMAT_R8G8B8A8_SNORM:
            return rdesc::ETextureFormat::RGBA8_SNORM;
        case VK_FORMAT_R8G8B8A8_UINT:
            return rdesc::ETextureFormat::RGBA8_UINT;
        case VK_FORMAT_R8G8B8A8_SINT:
            return rdesc::ETextureFormat::RGBA8_SINT;
        case VK_FORMAT_R8G8B8A8_SRGB:
            return rdesc::ETextureFormat::RGBA8_SRGB;
        case VK_FORMAT_R16G16B16A16_UNORM:
            return rdesc::ETextureFormat::RGBA16_UNORM;
        case VK_FORMAT_R16G16B16A16_SNORM:
            return rdesc::ETextureFormat::RGBA16_SNORM;
        case VK_FORMAT_R16G16B16A16_UINT:
            return rdesc::ETextureFormat::RGBA16_UINT;
        case VK_FORMAT_R16G16B16A16_SINT:
            return rdesc::ETextureFormat::RGBA16_SINT;
        case VK_FORMAT_R16G16B16A16_SFLOAT:
            return rdesc::ETextureFormat::RGBA16_SFLOAT;
        case VK_FORMAT_R32G32B32A32_UINT:
            return rdesc::ETextureFormat::RGBA32_UINT;
        case VK_FORMAT_R32G32B32A32_SINT:
            return rdesc::ETextureFormat::RGBA32_SINT;
        case VK_FORMAT_R32G32B32A32_SFLOAT:
            return rdesc::ETextureFormat::RGBA32_SFLOAT;
        case VK_FORMAT_B8G8R8A8_UNORM:
            return rdesc::ETextureFormat::BGRA8_UNORM;
        case VK_FORMAT_B8G8R8A8_SRGB:
            return rdesc::ETextureFormat::BGRA8_SRGB;
        case VK_FORMAT_D16_UNORM:
            return rdesc::ETextureFormat::D16_UNORM;
        case VK_FORMAT_D32_SFLOAT:
            return rdesc::ETextureFormat::D32_SFLOAT;
        case VK_FORMAT_D16_UNORM_S8_UINT:
            return rdesc::ETextureFormat::D16_UNORM_S8_UINT;
        case VK_FORMAT_D24_UNORM_S8_UINT:
            return rdesc::ETextureFormat::D24_UNORM_S8_UINT;
        case VK_FORMAT_D32_SFLOAT_S8_UINT:
            return rdesc::ETextureFormat::D32_SFLOAT_S8_UINT;
        case VK_FORMAT_BC1_RGB_UNORM_BLOCK:
            return rdesc::ETextureFormat::BC1_RGB_UNORM;
        case VK_FORMAT_BC1_RGB_SRGB_BLOCK:
            return rdesc::ETextureFormat::BC1_RGB_SRGB;
        case VK_FORMAT_BC1_RGBA_UNORM_BLOCK:
            return rdesc::ETextureFormat::BC1_RGBA_UNORM;
        case VK_FORMAT_BC1_RGBA_SRGB_BLOCK:
            return rdesc::ETextureFormat::BC1_RGBA_SRGB;
        case VK_FORMAT_BC2_UNORM_BLOCK:
            return rdesc::ETextureFormat::BC2_UNORM;
        case VK_FORMAT_BC2_SRGB_BLOCK:
            return rdesc::ETextureFormat::BC2_SRGB;
        case VK_FORMAT_BC3_UNORM_BLOCK:
            return rdesc::ETextureFormat::BC3_UNORM;
        case VK_FORMAT_BC3_SRGB_BLOCK:
            return rdesc::ETextureFormat::BC3_SRGB;
        case VK_FORMAT_BC4_UNORM_BLOCK:
            return rdesc::ETextureFormat::BC4_UNORM;
        case VK_FORMAT_BC4_SNORM_BLOCK:
            return rdesc::ETextureFormat::BC4_SNORM;
        case VK_FORMAT_BC5_UNORM_BLOCK:
            return rdesc::ETextureFormat::BC5_UNORM;
        case VK_FORMAT_BC5_SNORM_BLOCK:
            return rdesc::ETextureFormat::BC5_SNORM;
        case VK_FORMAT_BC6H_UFLOAT_BLOCK:
            return rdesc::ETextureFormat::BC6H_UFLOAT;
        case VK_FORMAT_BC6H_SFLOAT_BLOCK:
            return rdesc::ETextureFormat::BC6H_SFLOAT;
        case VK_FORMAT_BC7_UNORM_BLOCK:
            return rdesc::ETextureFormat::BC7_UNORM;
        case VK_FORMAT_BC7_SRGB_BLOCK:
            return rdesc::ETextureFormat::BC7_SRGB;
        default:
            return rdesc::ETextureFormat::UNDEFINED;
        }
    }
} // namespace lux::render::vulkan
