cmake_minimum_required(VERSION 3.22)
foreach(required SOURCE_DIR OUTPUT_ROOT PREFIX_PATH CPP_COMPONENT_ASSETS DEPENDENCY_ROOT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
if(EXISTS "${OUTPUT_ROOT}")
    message(FATAL_ERROR "Fresh OUTPUT_ROOT required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_ROOT}/source")
set(source "${OUTPUT_ROOT}/source")
set(build "${OUTPUT_ROOT}/build")
foreach(name CMakeLists.txt Behavior.hpp main.cpp behavior.symbols.json)
    file(COPY "${SOURCE_DIR}/${name}" DESTINATION "${source}")
endforeach()
# A private input-mutation fixture copied verbatim from the SDK, not a repair of the installed package.
file(COPY "${CPP_COMPONENT_ASSETS}/cmake_scripts" DESTINATION "${source}/script_codegen")
file(READ "${source}/CMakeLists.txt" project)
string(REPLACE "include_component_cmake_scripts(lux::engine::simulation::simulation_script_cpp_static)"
    "include(\"\${CMAKE_CURRENT_SOURCE_DIR}/script_codegen/cmake_scripts/lux_cpp_static_scripts.cmake\")"
    project "${project}")
string(APPEND project "\nif(INCREMENTAL_MACRO)\n target_compile_definitions(lux_cpp_generated_script_consumer PRIVATE INCREMENTAL_PROBE=1)\nendif()\n")
string(APPEND project "if(INCREMENTAL_OPTION)\n target_compile_options(lux_cpp_generated_script_consumer PRIVATE /DINCREMENTAL_PROBE=1)\nendif()\n")
file(WRITE "${source}/CMakeLists.txt" "${project}")
file(WRITE "${source}/Dependency.hpp" "#pragma once\ninline constexpr int kIncrement = 1;\n")
file(READ "${source}/Behavior.hpp" behavior)
string(REPLACE "\r\n" "\n" behavior "${behavior}")
string(REPLACE "#pragma once" "#pragma once\n#include \"Dependency.hpp\"" behavior "${behavior}")
string(REPLACE "public:\n" "public:\n#if INCREMENTAL_PROBE\n        LUX_METHOD(script_export=\"missing.probe\")\n        void probe() noexcept {}\n#endif\n" behavior "${behavior}")
file(WRITE "${source}/Behavior.hpp" "${behavior}")

function(configure phase)
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${build}" -G Ninja
        -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF
        "-DCMAKE_PREFIX_PATH=${PREFIX_PATH}" "-DVCPKG_INSTALLED_DIR=${DEPENDENCY_ROOT}"
        -DCMAKE_TOOLCHAIN_FILE=D:/Development/vcpkg/scripts/buildsystems/vcpkg.cmake ${ARGN}
        RESULT_VARIABLE status OUTPUT_FILE "${OUTPUT_ROOT}/${phase}-configure.log"
        ERROR_FILE "${OUTPUT_ROOT}/${phase}-configure-error.log")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "${phase} configure failed")
    endif()
endfunction()
function(build_and_run phase expected_error)
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${build}" --target all -j 4 -- -k 0
        RESULT_VARIABLE status OUTPUT_FILE "${OUTPUT_ROOT}/${phase}-build.log"
        ERROR_FILE "${OUTPUT_ROOT}/${phase}-build-error.log")
    if(NOT expected_error STREQUAL "")
        file(READ "${OUTPUT_ROOT}/${phase}-build.log" output)
        file(READ "${OUTPUT_ROOT}/${phase}-build-error.log" error)
        if(status EQUAL 0 OR NOT "${output}\n${error}" MATCHES "${expected_error}")
            message(FATAL_ERROR "${phase} did not fail for its expected semantic reason")
        endif()
        return()
    endif()
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "${phase} build failed; no stale executable run")
    endif()
    execute_process(COMMAND "${build}/lux_cpp_generated_script_consumer.exe"
        RESULT_VARIABLE status OUTPUT_FILE "${OUTPUT_ROOT}/${phase}-run.log"
        ERROR_FILE "${OUTPUT_ROOT}/${phase}-run-error.log")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "${phase} runtime failed (${status})")
    endif()
endfunction()
function(snapshot result)
    file(GLOB_RECURSE outputs "${build}/generated/*.script.generated.*" "${build}/generated/*.bindings.json")
    if(NOT outputs)
        message(FATAL_ERROR "Generated outputs missing")
    endif()
    list(SORT outputs)
    set(records)
    foreach(path IN LISTS outputs)
        file(SHA256 "${path}" hash)
        file(TIMESTAMP "${path}" timestamp "%s" UTC)
        list(APPEND records "${path}|${hash}|${timestamp}")
    endforeach()
    set(${result} "${records}" PARENT_SCOPE)
endfunction()

configure(initial -DINCREMENTAL_MACRO=OFF -DINCREMENTAL_OPTION=OFF)
build_and_run(initial "")
snapshot(original)
string(REPLACE "observed = ++value_;" "observed = (value_ += kIncrement);" behavior "${behavior}")
file(WRITE "${source}/Behavior.hpp" "${behavior}")
build_and_run(body "")
snapshot(after_body)
if(NOT after_body STREQUAL original)
    message(FATAL_ERROR "Body-only change rewrote fixed generated outputs")
endif()
file(WRITE "${source}/Dependency.hpp" "#pragma once\ninline constexpr int kIncrement = (1 + 0);\n")
build_and_run(transitive "")
file(READ "${OUTPUT_ROOT}/transitive-build.log" transitive_log)
if(NOT transitive_log MATCHES "Parsed [1-9]" OR NOT transitive_log MATCHES "Building CXX")
    message(FATAL_ERROR "Transitive include did not invalidate parsing and compilation")
endif()
file(READ "${source}/behavior.symbols.json" ledger)
string(REPLACE "\"symbol\":1}" "\"symbol\":5}" ledger "${ledger}")
string(REPLACE "\"next_symbol\":5" "\"next_symbol\":6" ledger "${ledger}")
file(WRITE "${source}/behavior.symbols.json" "${ledger}")
build_and_run(ledger "")
snapshot(after_ledger)
if(after_ledger STREQUAL after_body)
    message(FATAL_ERROR "Used lifecycle symbol change did not regenerate its contract")
endif()
configure(macro -DINCREMENTAL_MACRO=ON)
build_and_run(macro "missing stable symbol")
configure(option -DINCREMENTAL_MACRO=OFF -DINCREMENTAL_OPTION=ON)
build_and_run(option "missing stable symbol")
configure(restored -DINCREMENTAL_OPTION=OFF)
build_and_run(restored "")
set(template "${source}/script_codegen/cmake_scripts/template/cpp_static_script.template")
file(APPEND "${template}" "\n// incremental-template-input-proof\n")
build_and_run(template "")
snapshot(after_template)
if(after_template STREQUAL after_ledger)
    message(FATAL_ERROR "Template modification did not regenerate outputs")
endif()
set(validation "${source}/script_codegen/cmake_scripts/template/cpp_static_script.validation.template")
file(READ "${validation}" valid_template)
file(WRITE "${validation}" "{\"diagnostics\":[{\"severity\":\"error\",\"declaration\":\"fixture\",\"message\":\"injected validation failure\"}]}")
build_and_run(validation "injected validation failure")
snapshot(after_failure)
if(NOT after_failure STREQUAL after_template)
    message(FATAL_ERROR "Validation failure modified published outputs")
endif()
file(WRITE "${validation}" "${valid_template}")
build_and_run(recovered "")
build_and_run(noop "")
file(READ "${OUTPUT_ROOT}/noop-build.log" output)
if(NOT output MATCHES "no work to do")
    message(FATAL_ERROR "Final build is not a no-op")
endif()
message(STATUS "Source/include/ledger/macro/target-option/template/validation/no-op closure passed")
