add_library(sample_external_editor_legacy SHARED ExternalEditor.cpp)
include(GenerateExportHeader)
generate_export_header(sample_external_editor_legacy EXPORT_FILE_NAME SampleEditorExport.hpp EXPORT_MACRO_NAME SAMPLE_EXTERNAL_EDITOR_EXPORT)
target_include_directories(sample_external_editor_legacy PRIVATE "${CMAKE_CURRENT_BINARY_DIR}")
target_link_libraries(sample_external_editor_legacy PRIVATE lux::engine::editor::editor_extensions_legacy)
set(sample_editor_argument EDITOR_TARGET sample_external_editor_legacy PARENT_SCOPE)
add_executable(sample_editor_test_legacy ExternalEditorTest.cpp)
target_link_libraries(sample_editor_test_legacy PRIVATE lux::engine::editor::editor_bootstrap_legacy lux::engine::editor::project_module_legacy)
if(MSVC)
    target_compile_options(sample_external_editor_legacy PRIVATE /utf-8)
    target_compile_options(sample_editor_test_legacy PRIVATE /UNDEBUG /utf-8)
else()
    target_compile_options(sample_editor_test_legacy PRIVATE -UNDEBUG)
endif()
add_dependencies(sample_editor_test_legacy sample_external_editor_legacy)
add_test(NAME legacy.plugin.external_editor COMMAND sample_editor_test_legacy "${CMAKE_BINARY_DIR}")
set_tests_properties(legacy.plugin.external_editor PROPERTIES TIMEOUT 60 RUN_SERIAL TRUE)
