function(engine_target_add_imgui_inspector_codegen)
    set(one NAME TARGET HEADER LOGICAL_PATH SOURCE_FILE OUTPUT_ROOT)
    set(multi COMPONENTS CUSTOM_HEADERS CUSTOM_TYPES DEPENDS)
    cmake_parse_arguments(ARG "" "${one}" "${multi}" ${ARGN})
    foreach(required NAME TARGET HEADER LOGICAL_PATH COMPONENTS SOURCE_FILE)
        if(NOT ARG_${required})
            message(FATAL_ERROR "Editor Inspector codegen requires ${required}")
        endif()
    endforeach()
    get_target_property(layer ${ARG_TARGET} LUX_ARCH_LAYER)
    if(NOT layer STREQUAL "EDITOR")
        message(FATAL_ERROR "Editor Inspector output requires an EDITOR target: ${ARG_TARGET}")
    endif()
    get_target_property(owned_components ${ARG_TARGET} LUX_EDITOR_INSPECTOR_COMPONENTS)
    foreach(component IN LISTS ARG_COMPONENTS)
        if(component IN_LIST owned_components)
            message(FATAL_ERROR "Duplicate Inspector implementation in target ${ARG_TARGET}: ${component}")
        endif()
        list(APPEND owned_components "${component}")
    endforeach()
    set_property(TARGET ${ARG_TARGET} PROPERTY LUX_EDITOR_INSPECTOR_COMPONENTS ${owned_components})
    find_package(Python3 REQUIRED COMPONENTS Interpreter)
    if(EXISTS "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../codegen/inspector_codegen.py")
        set(generator_dir "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../codegen")
        find_package(imgui REQUIRED COMPONENTS core)
        set(backend imgui::core)
    else()
        set(generator_dir "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/codegen")
        # Pin the same shared backend used by this SDK. This is an imported dependency, not a new DLL/context.
        if(NOT TARGET lux_editor_inspector_imgui)
            get_filename_component(sdk_prefix "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../../.." ABSOLUTE)
            add_library(lux_editor_inspector_imgui SHARED IMPORTED GLOBAL)
            set_target_properties(lux_editor_inspector_imgui PROPERTIES
                IMPORTED_IMPLIB "${sdk_prefix}/lib/imgui_core.lib"
                IMPORTED_LOCATION "${sdk_prefix}/bin/imgui_core.dll"
                INTERFACE_INCLUDE_DIRECTORIES "${generator_dir}/backend"
                INTERFACE_COMPILE_DEFINITIONS IMGUI_SHARED_CORE)
        endif()
        set(backend lux_editor_inspector_imgui)
    endif()
    if(NOT ARG_OUTPUT_ROOT)
        set(ARG_OUTPUT_ROOT "${CMAKE_CURRENT_BINARY_DIR}/inspector_gen/${ARG_NAME}")
    endif()
    set(ir_root "${CMAKE_CURRENT_BINARY_DIR}/inspector_ir/${ARG_NAME}")
    lux_add_codegen_job(NAME ${ARG_NAME}_ir MARKER luxref SOURCE_FILE ${ARG_SOURCE_FILE}
        TARGET_FILES ${ARG_HEADER} LOGICAL_PATHS ${ARG_LOGICAL_PATH} DEPENDS ${ARG_DEPENDS})
    lux_codegen_add_projection(JOB ${ARG_NAME}_ir NAME editor_ir
        TEMPLATE "${generator_dir}/ir.template" OUTPUT_ROOT "${ir_root}" OUTPUT_SUFFIX .editor-ir SERIAL_META)
    lux_target_add_codegen(TARGET ${ARG_TARGET} JOB ${ARG_NAME}_ir DONT_ADD_TO_SOURCE DONT_INCLUDE)
    get_filename_component(logical_dir "${ARG_LOGICAL_PATH}" DIRECTORY)
    get_filename_component(stem "${ARG_LOGICAL_PATH}" NAME_WE)
    set(ir "${ir_root}/${logical_dir}/${stem}.editor-ir.json")
    set(config "${CMAKE_CURRENT_BINARY_DIR}/lux_codegen/${ARG_NAME}.inspector.json")
    foreach(key NAME LOGICAL_PATH OUTPUT_ROOT)
        _meta_json_escape(json_${key} "${ARG_${key}}")
    endforeach()
    set(json "{\"name\":\"${json_NAME}\",\"logical_path\":\"${json_LOGICAL_PATH}\",\"output_root\":\"${json_OUTPUT_ROOT}\"")
    foreach(key COMPONENTS CUSTOM_HEADERS CUSTOM_TYPES)
        string(TOLOWER "${key}" json_key)
        string(APPEND json ",\"${json_key}\":[")
        set(separator "")
        foreach(value IN LISTS ARG_${key})
            _meta_json_escape(escaped "${value}")
            string(APPEND json "${separator}\"${escaped}\"")
            set(separator ",")
        endforeach()
        string(APPEND json "]")
    endforeach()
    string(APPEND json "}\n")
    file(GENERATE OUTPUT "${config}" CONTENT "${json}")
    set(outputs "${ARG_OUTPUT_ROOT}/${ARG_NAME}.inspector.generated.hpp")
    foreach(component IN LISTS ARG_COMPONENTS)
        string(REGEX REPLACE "[^A-Za-z0-9_]" "_" component_symbol "${component}")
        string(SHA256 digest "${component}")
        string(SUBSTRING "${digest}" 0 8 digest)
        list(APPEND outputs "${ARG_OUTPUT_ROOT}/${component_symbol}_${digest}.inspector.generated.cpp")
    endforeach()
    get_target_property(meta_generator ${ARG_NAME}_ir LUX_CODEGEN_GENERATOR)
    add_custom_command(OUTPUT ${outputs} "${ir}"
        COMMAND "${Python3_EXECUTABLE}" "${generator_dir}/inspector_codegen.py" --config "${config}" --ir "${ir}"
            --meta-generator "${meta_generator}" --meta-config "${CMAKE_CURRENT_BINARY_DIR}/lux_codegen/${ARG_NAME}_ir.json"
        DEPENDS "${ir_root}/${logical_dir}/${stem}.editor-ir" "${config}" ${ARG_DEPENDS}
            "${generator_dir}/inspector_codegen.py" "${generator_dir}/support/InspectorWidget.hpp"
        COMMENT "Generate Editor-only ImGui Inspector: ${ARG_NAME}" VERBATIM)
    target_sources(${ARG_TARGET} PRIVATE ${outputs})
    set_source_files_properties(${outputs} PROPERTIES GENERATED TRUE)
    target_include_directories(${ARG_TARGET} PRIVATE "${ARG_OUTPUT_ROOT}" "${generator_dir}/support")
    target_link_libraries(${ARG_TARGET} PRIVATE ${backend})
    set_property(TARGET ${ARG_TARGET} APPEND PROPERTY LUX_EDITOR_INSPECTOR_GENERATED_SOURCES ${outputs})
endfunction()
