cmake_minimum_required(VERSION 3.24)
project(p11_r1_before LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
find_package(lux-engine-editor-extensions REQUIRED COMPONENTS editor_extensions)
find_package(lux-engine-editor-persistence REQUIRED COMPONENTS editor_persistence_execution)
find_package(lux-engine-editor-file-publication REQUIRED COMPONENTS editor_file_publication)
add_executable(models models.cpp)
add_executable(contributions contributions.cpp)
foreach(t models contributions)
 target_link_libraries(${t} PRIVATE lux::engine::editor::editor_extensions lux::engine::editor::editor_persistence_execution lux::engine::editor::editor_file_publication)
 target_compile_options(${t} PRIVATE /UNDEBUG /utf-8 /permissive- /Zc:__cplusplus /Zc:preprocessor)
endforeach()
