add_subdirectory(editing)
add_subdirectory(project)
add_subdirectory(storage)
add_subdirectory(assets)
add_subdirectory(metadata)
add_subdirectory(plugins)
add_subdirectory(editing/scene)
add_subdirectory(context)
add_subdirectory(ui)
add_subdirectory(tools)
add_subdirectory(launcher)
add_subdirectory(app)
