include_guard(GLOBAL)

function(lux_script_semantic_schema)
    cmake_parse_arguments(ARGS "" "NAME;OUTPUT" "TYPES;HEADERS;TARGETS;INCLUDE_DIRECTORIES" ${ARGN})
    if(NOT ARGS_NAME OR NOT ARGS_OUTPUT)
        message(FATAL_ERROR "[lux_script_semantic_schema] NAME and OUTPUT are required")
    endif()
    if(CMAKE_CROSSCOMPILING)
        message(FATAL_ERROR "[lux_script_semantic_schema] supply a schema produced by the target, not a host writer")
    endif()
    set(schema_includes "")
    foreach(header IN LISTS ARGS_HEADERS)
        string(APPEND schema_includes "#include <${header}>\n")
    endforeach()
    set(schema_types "")
    foreach(type IN LISTS ARGS_TYPES)
        string(APPEND schema_types "        lux::script::scriptSemanticLayout<${type}>(),\n")
    endforeach()
    list(LENGTH ARGS_TYPES schema_type_count)
    set(writer "${CMAKE_CURRENT_BINARY_DIR}/${ARGS_NAME}.schema.cpp")
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/script_semantic_schema.cpp.in" "${writer}" @ONLY)
    add_executable(${ARGS_NAME}_writer EXCLUDE_FROM_ALL "${writer}")
    target_compile_features(${ARGS_NAME}_writer PRIVATE cxx_std_20)
    target_link_libraries(${ARGS_NAME}_writer PRIVATE lux::engine::function::script_core ${ARGS_TARGETS})
    target_include_directories(${ARGS_NAME}_writer PRIVATE ${ARGS_INCLUDE_DIRECTORIES})
    add_custom_command(OUTPUT "${ARGS_OUTPUT}" COMMAND ${ARGS_NAME}_writer "${ARGS_OUTPUT}"
        DEPENDS ${ARGS_NAME}_writer VERBATIM)
    add_custom_target(${ARGS_NAME} DEPENDS "${ARGS_OUTPUT}")
    if(COMMAND lux_classify_target)
        lux_classify_target(TARGET ${ARGS_NAME}_writer LAYER TOOLCHAIN PRODUCT BUILD_TOOL ROLE DOMAIN)
        lux_classify_target(TARGET ${ARGS_NAME} LAYER TOOLCHAIN PRODUCT BUILD_TOOL ROLE DOMAIN)
    endif()
endfunction()
