execute_process(COMMAND "${CMAKE_COMMAND}" --build "${BUILD_DIR}" --target "${PROBE}" -j 4 -- -k 0
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
set(log "${output}\n${error}")
file(WRITE "${BUILD_DIR}/${PROBE}.log" "${log}")
if(result EQUAL 0)
    message(FATAL_ERROR "${PROBE}: illegal operation unexpectedly compiled")
endif()
if(NOT log MATCHES "(C2280|deleted function|deleted constructor|deleted operator|explicitly deleted)")
    message(FATAL_ERROR "${PROBE}: failure was not a deleted special member:\n${log}")
endif()
if(log MATCHES "(C1083|fatal error:.*file not found|cannot open include|No such file or directory)")
    message(FATAL_ERROR "${PROBE}: missing dependency is not a contract rejection:\n${log}")
endif()
message(STATUS "${PROBE}: compiler rejected the deleted special member")
