if(NOT DEFINED FILES OR FILES STREQUAL "")
    message(FATAL_ERROR "FILES is required")
endif()

foreach(file IN LISTS FILES)
    if(NOT EXISTS "${file}")
        message(FATAL_ERROR "Generated Inspector projection is missing: ${file}")
    endif()
    file(READ "${file}" content)
    if(content MATCHES "imgui|ImGui|ImVec[24]|ImTextureID|ImDraw(Data|List)|RefClass|RefField|ReflectionRegistry")
        message(FATAL_ERROR "Generated Inspector projection leaks backend/reflection vocabulary: ${file}")
    endif()
endforeach()
