from pathlib import Path
import json
w=Path(r'E:/SyncForder/CodeRepos/lux-engine/.internal/editor-redesign/P11')
old=w.parent/'layering'
s=(old/'qualify.py').read_text().replace('lux-engine-p10q-structure','lux-engine-p11').replace('p10q-structure','p11').replace('P10Q-structure','P11').replace('P10Q commit','P11 commit').replace('-DLUX_EDITOR_MIGRATION_STAGE=P10Q','-DLUX_EDITOR_MIGRATION_STAGE=P11')
s=s.replace('import argparse, hashlib, json, os, shutil, subprocess, sys','import argparse, hashlib, json, os, shutil, subprocess, sys\nfrom datetime import datetime, timezone')
s=s.replace('    with log.open(\'wb\') as stream:r=subprocess.run(args,cwd=cwd,stdout=stream,stderr=subprocess.STDOUT)',"    started=datetime.now(timezone.utc).isoformat()\n    with log.open('wb') as stream:r=subprocess.run(args,cwd=cwd,stdout=stream,stderr=subprocess.STDOUT)\n    ended=datetime.now(timezone.utc).isoformat()")
s=s.replace("'implementation_sha':sha})","'implementation_sha':sha,'started':started,'ended':ended})")
s=s.replace("work/'dependency-seed-source.json'","work.parent/'layering/dependency-seed-source.json'")
s=s.replace("build/'bin',1)","build/'bin',0 if defect=='C03' else 1)")
(w/'qualify.py').write_text(s)
s=(old/'run_sdk.py').read_text().replace('import os,subprocess,json,shutil,hashlib,argparse','import os,subprocess,json,shutil,hashlib,argparse\nfrom datetime import datetime, timezone')
s=s.replace(" with log.open('wb') as stream:r=subprocess.run(args,cwd=cwd,stdout=stream,stderr=subprocess.STDOUT)"," started=datetime.now(timezone.utc).isoformat()\n with log.open('wb') as stream:r=subprocess.run(args,cwd=cwd,stdout=stream,stderr=subprocess.STDOUT)\n ended=datetime.now(timezone.utc).isoformat()")
s=s.replace("'argv':args,'exit_code'","'argv':args,'cwd':str(cwd),'started':started,'ended':ended,'exit_code'")
s=s.replace("groups={","groups={\n 'p11':('editor-p11',[f'-DSDK_PREFIX={prefix.as_posix()}']),\n 'p11-runtime':('editor-p11/runtime',[f'-DSDK_PREFIX={prefix.as_posix()}']),\n 'p11-models':('editor-p11/models',[]),")
s=s.replace("copies={","copies={\n 'p11-models':[('editor/tests/integration/session_factories/installation.cpp','installation.cpp')],")
(w/'run_sdk.py').write_text(s)
s=(old/'check_headers.py').read_text().replace('lux-engine-p10q-structure','lux-engine-p11').replace('P10Q-structure','P11').replace('f7c27f9375cbf8dd8af37b30a6027a460de26213','22ab1a30862f6bff943cef86d4232839173c7107')
s=s.replace('import subprocess, hashlib, json, os','import subprocess, hashlib, json, os\nfrom datetime import datetime, timezone')
s=s.replace("    with log.open('wb') as stream:result=subprocess.run(args,cwd=repo,stdout=stream,stderr=subprocess.STDOUT)","    started=datetime.now(timezone.utc).isoformat()\n    with log.open('wb') as stream:result=subprocess.run(args,cwd=repo,stdout=stream,stderr=subprocess.STDOUT)\n    ended=datetime.now(timezone.utc).isoformat()")
s=s.replace("'source':path,'argv':args","'source':path,'argv':args,'started':started,'ended':ended")
(w/'check_headers.py').write_text(s)
