add_component(COMPONENT_NAME platform_process NAMESPACE lux::engine::platform STATIC SOURCE_FILES src/Process.cpp)
component_include_directories(platform_process BUILD_TIME_EXPORT ${CMAKE_CURRENT_SOURCE_DIR}/include INSTALL_TIME include)
target_link_libraries(platform_process PUBLIC lux::cxx::compile_time)
if(WIN32)
    target_link_libraries(platform_process PRIVATE shell32 ole32)
endif()
component_add_transitive_commands(platform_process "find_package(lux-cxx REQUIRED COMPONENTS compile_time)")
lux_classify_target(TARGET platform_process LAYER MODULES PRODUCT SHARED ROLE LIBRARY)

if(BUILD_TESTING)
    add_executable(platform_process_arguments test/arguments.cpp)
    target_link_libraries(platform_process_arguments PRIVATE platform_process)
    if(MSVC)
        target_compile_options(platform_process_arguments PRIVATE /UNDEBUG /utf-8)
    else()
        target_compile_options(platform_process_arguments PRIVATE -UNDEBUG)
    endif()
    add_test(NAME platform.process_arguments COMMAND platform_process_arguments "${CMAKE_CURRENT_BINARY_DIR}/arguments")
    set_tests_properties(platform.process_arguments PROPERTIES TIMEOUT 20)
endif()
