/**
 * @file RenderableBridgeContext.cpp
 *
 * Shared bridge-facing helpers extracted from `RenderableSystem::Impl`.
 * All `ensure*` / `acquire*` / `release*` bodies live here; bridges
 * call into the context to acquire / release GPU resources without
 * knowing anything about the cache layout or RenderSession internals.
 */

#include "lux/engine/render_bridge/RenderableBridgeContext.hpp"

#include <iostream>
#include <span>

#include <lux/engine/asset/AssetManager.hpp>
#include <lux/engine/description/ShaderInfo.hpp>        // ShaderInfo::serialize
#include <lux/engine/description/Texture.hpp>          // isCompressedFormat
#include <lux/engine/render/comm/client/RenderSession.hpp>

namespace lux::render_bridge
{
    RenderableBridgeContext::RenderableBridgeContext(
        lux::render::RenderSession& session,
        lux::asset::AssetManager&   mgr,
        lux::render::RenderSceneId  scene_id,
        lux::render::ViewHandle     view,
        lux::ecs::AssetLoadFn                 request_load) noexcept
        : session_(&session)
        , mgr_(&mgr)
        , scene_(scene_id)
        , view_(view)
        , request_load_(std::move(request_load))
    {
        // No async loader wired → synchronous fallback so un-wired headless /
        // tool processes still materialize an absent asset on first reference
        // (mirrors the one-shot ensureAsset the old AssetHandle ctor did).
        if (!request_load_)
            request_load_ = [this](const lux::asset::asset_id_t& id)
            {
                (void)mgr_->ensureAsset(id);
            };
    }

    // ── ensure* ────────────────────────────────────────────────────────

    lux::render::RMeshHandle
    RenderableBridgeContext::ensureMesh(const lux::asset::asset_id_t& id)
    {
        if (id.is_nil()) return {};
        auto [it, inserted] = mesh_resources_.try_emplace(id);
        auto& entry = it->second;
        (void)inserted;

        if (!entry.pending && (!entry.gpu_handle.is_null() || entry.failed))
            return entry.gpu_handle;
        if (entry.pending) return {};

        // Re-query the CPU asset (cheap, keyed by the same id this entry lives
        // under). Absent / data-less shell → fire the async loader and return a
        // null handle this frame; a later frame finds the injected data + uploads.
        const auto* mesh = mgr_->fetchAssetAs<lux::asset::MeshAsset>(id);
        if (mesh == nullptr || mesh->data() == nullptr)
        {
            request_load_(id);
            return {};
        }

        entry.pending = true;
        trackThen(meshStack().uploadMesh(*mesh->data()),
            [this, id](const lux::render::MeshUploadedReply& r)
            {
                auto rit = mesh_resources_.find(id);
                if (rit == mesh_resources_.end()) return;
                // Validate BOTH status and handle: a generic dispatch failure delivers a
                // DEFAULT reply {status 0, null handle}, which status-only would read as
                // success → {pending 0, failed 0, gpu_handle null} = the "never attempted"
                // state → a per-frame re-upload loop. Route it to failed instead (P1-4).
                const bool ok = (r.status == 0 && !r.handle.is_null());
                rit->second.pending    = false;
                rit->second.gpu_handle = ok ? r.handle : lux::render::RMeshHandle{};
                if (!ok)
                {
                    rit->second.failed = true;
                    std::cerr << "[RenderableSystem] mesh upload failed (status="
                              << r.status << "); instance will not render\n";
                }
            });
        return {};
    }

    lux::render::RTextureHandle
    RenderableBridgeContext::ensureTexture(const lux::asset::asset_id_t& id)
    {
        if (id.is_nil()) return {};
        auto [it, inserted] = texture_resources_.try_emplace(id);
        auto& entry = it->second;
        (void)inserted;

        if (!entry.pending && (entry.gpu_handle.is_null() == false || entry.failed))
            return entry.gpu_handle;
        if (entry.pending) return {};

        const auto* tex_asset = mgr_->fetchAssetAs<lux::asset::TextureAsset>(id);
        if (tex_asset == nullptr || tex_asset->data() == nullptr)
        {
            request_load_(id);
            return {};
        }

        const lux::rdesc::Texture& tex = *tex_asset->data();
        // Format-validity check now lives in render::toPixelFormat (invoked
        // by the rdesc-typed createTexture2D overload). On unsupported
        // formats the request resolves synchronously with status!=0 -> the
        // .then callback below sets entry.failed without a wire dispatch.
        //
        // Mip chain: generated by DEFAULT (imported material textures ship mip 0
        // only and want minification filtering), unless the asset carries the
        // author's NO_MIPS intent — tileset atlases, pixel-art sheets, lookup
        // textures, whose minified average is meaningless or actively wrong.
        // Compressed formats never generate (their chain is baked or absent).
        const bool generate_mips =
            !lux::rdesc::isCompressedFormat(tex.pixelFormat()) &&
            !lux::rdesc::hasTextureFlag(tex.flags(), lux::rdesc::ETextureAssetFlags::NO_MIPS);
        entry.pending = true;
        trackThen(session_->createTexture2D(
            static_cast<const std::byte*>(tex.data()),
            static_cast<std::uint32_t>(tex.size()),
            tex.width(), tex.height(), tex.channel(), tex.pixelFormat(),
            generate_mips),
            [this, id](const lux::render::Texture2DCreatedReply& r)
            {
                auto rit = texture_resources_.find(id);
                if (rit == texture_resources_.end()) return;
                // Validate handle too, not just status (P1-4 — see ensureMesh): a
                // default dispatch-failure reply {status 0, null handle} must route to
                // failed, not settle as a ready-but-null texture that re-uploads forever.
                const bool ok = (r.status == 0 && !r.handle.is_null());
                rit->second.pending    = false;
                rit->second.gpu_handle = ok ? r.handle : lux::render::RTextureHandle{};
                if (!ok)
                {
                    rit->second.failed = true;
                    std::cerr << "[RenderableSystem] texture upload failed (status="
                              << r.status << "); material/instance may render untextured\n";
                }
            });
        return {};
    }

    lux::render::RMaterialHandle
    RenderableBridgeContext::ensureMaterial(const lux::asset::asset_id_t& id)
    {
        if (id.is_nil()) return {};

        // Every material is a node-graph material now — the builtin closure render
        // path is RETIRED (W5a). Dispatch by asset TYPE so bridges stay material-
        // kind agnostic (they call ensureMaterial only); queryInfo() reads the
        // registered type WITHOUT loading the asset data.
        const auto* info = mgr_->queryInfo(id);
        if (!info) return {};
        if (info->type == lux::asset::EAssetType::MATERIAL)
        {
            material_instance_resources_.erase(id);   // keep the two graph caches disjoint
            return ensureGraphMaterial(id);
        }
        if (info->type == lux::asset::EAssetType::MATERIAL_INSTANCE)
        {
            graph_material_resources_.erase(id);
            return ensureMaterialInstance(id);
        }
        // Builtin/unknown material types no longer render — re-import to a graph material.
        return {};
    }

    // ── ensureGraphMaterial ─────────────────────────────────────────────
    // A graph material's runtime artifacts are BAKED (gbuffer/forward SPIR-V +
    // ShaderInfo + param defaults + texture-slot UUIDs); gameplay never touches
    // the graph compiler. Bringing one up is a small async state machine, each
    // stage gated on the previous reply:
    //   (1) compileShader(gbuffer_spirv, gbuffer_info)  -> gbuffer_shader
    //   (2) compileShader(forward_spirv, forward_info)  -> forward_shader (opt.)
    //   (3) ensureTexture(slot uuid) for each bound slot -> settle to bindless
    //   (4) uploadGraphMaterial(data, gbuffer_shader, forward_shader) -> handle
    // The material gets its OWN variant bucket / PSO from the two frags (R1).
    lux::render::RMaterialHandle
    RenderableBridgeContext::ensureGraphMaterial(const lux::asset::asset_id_t& id)
    {
        auto [it, inserted] = graph_material_resources_.try_emplace(id);
        auto& e = it->second;
        (void)inserted;

        if (!e.gpu_handle.is_null()) return e.gpu_handle;  // ready
        if (e.failed)                return {};            // known-bad, no retry

        const auto* mat_asset = mgr_->fetchAssetAs<lux::asset::MaterialAsset>(id);
        if (mat_asset == nullptr || mat_asset->data() == nullptr)
        {
            request_load_(id);                             // async-load the asset
            return {};                                     // not loaded yet
        }
        const lux::asset::MaterialData& payload = *mat_asset->data();

        // ── Stage 1: compile the deferred GBuffer frag (required) ──
        if (!e.gbuffer_ready)
        {
            if (e.gbuffer_in_flight) return {};
            if (payload.gbuffer_spirv.empty())
            {
                e.failed = true;
                std::cerr << "[RenderableSystem] graph material has no GBuffer "
                             "SPIR-V; instance will not render\n";
                return {};
            }
            // Snapshot SPIR-V + serialized info into the entry: compileShader
            // borrows BOTH until submitFrame(), and the asset vectors are not
            // pinned against eviction (the bridge only re-queries the asset).
            e.gbuffer_spirv_copy = payload.gbuffer_spirv;
            e.gbuffer_info_bytes =
                lux::rdesc::ShaderInfo::serialize(payload.gbuffer_info);
            e.gbuffer_in_flight = true;
            const auto spv = std::span<const std::byte>{
                reinterpret_cast<const std::byte*>(e.gbuffer_spirv_copy.data()),
                e.gbuffer_spirv_copy.size() * sizeof(std::uint32_t)};
            trackThen(session_->compileShader(
                spv,
                std::span<const std::byte>{e.gbuffer_info_bytes.data(),
                                           e.gbuffer_info_bytes.size()}),
                [this, id](const lux::render::ShaderCompiledReply& r)
                {
                    auto rit = graph_material_resources_.find(id);
                    if (rit == graph_material_resources_.end()) return;
                    rit->second.gbuffer_in_flight = false;
                    if (r.status == 0 && !r.shader.is_null())
                    {
                        rit->second.gbuffer_shader = r.shader;
                        rit->second.gbuffer_ready  = true;
                    }
                    else
                    {
                        rit->second.failed = true;
                        std::cerr << "[RenderableSystem] graph GBuffer shader "
                                     "compile failed (status=" << r.status
                                  << "); instance will not render\n";
                    }
                });
            return {};
        }

        // ── Stage 2: compile the Forward frag (optional; non-fatal on failure) ──
        const bool need_forward = !payload.forward_spirv.empty();
        if (need_forward && !e.forward_ready)
        {
            if (e.forward_in_flight) return {};
            e.forward_spirv_copy = payload.forward_spirv;
            e.forward_info_bytes =
                lux::rdesc::ShaderInfo::serialize(payload.forward_info);
            e.forward_in_flight = true;
            const auto spv = std::span<const std::byte>{
                reinterpret_cast<const std::byte*>(e.forward_spirv_copy.data()),
                e.forward_spirv_copy.size() * sizeof(std::uint32_t)};
            trackThen(session_->compileShader(
                spv,
                std::span<const std::byte>{e.forward_info_bytes.data(),
                                           e.forward_info_bytes.size()}),
                [this, id](const lux::render::ShaderCompiledReply& r)
                {
                    auto rit = graph_material_resources_.find(id);
                    if (rit == graph_material_resources_.end()) return;
                    rit->second.forward_in_flight = false;
                    rit->second.forward_ready     = true;   // proceed either way
                    if (r.status == 0 && !r.shader.is_null())
                        rit->second.forward_shader = r.shader;
                    else
                        std::cerr << "[RenderableSystem] graph forward shader "
                                     "compile failed (status=" << r.status
                                  << "); forward pass falls back to the family "
                                     "frag\n";
                });
            return {};
        }

        // ── Stage 3: resolve each bound texture slot to a bindless index ──
        // Snapshot the slot ids (incl. nils, slot order preserved) so the 1->0
        // release path can still walk them after the source asset is evicted.
        if (e.texture_ids.empty())
            for (const auto& tid : payload.texture_slot_ids)
                e.texture_ids.push_back(tid);

        bool all_settled = true;
        for (const auto& tid : payload.texture_slot_ids)
        {
            if (tid.is_nil()) continue;
            (void)ensureTexture(tid);
            auto tit = texture_resources_.find(tid);
            if (tit == texture_resources_.end()) { all_settled = false; continue; }
            if (tit->second.pending) all_settled = false;
        }
        if (!all_settled) return {};

        // ── Stage 4: build GraphMaterialData + upload (carries its own frags) ──
        if (e.upload_in_flight) return {};

        static_assert(lux::render::GraphMaterialData::kMaxParams ==
                          lux::asset::MaterialData::kMaxParams,
                      "graph param-lane capacity must match across the asset/render boundary");
        lux::render::GraphMaterialData gd{};
        // Derive the param lanes from the authoring graph (the SSOT): a base
        // material's param VALUES are its graph param-slot defaults.
        const auto& base_pslots = payload.graph.param_slots;
        gd.param_count = static_cast<std::uint32_t>(
            base_pslots.size() < lux::render::GraphMaterialData::kMaxParams
                ? base_pslots.size() : lux::render::GraphMaterialData::kMaxParams);
        for (std::uint32_t i = 0; i < lux::render::GraphMaterialData::kMaxParams; ++i)
            for (std::uint32_t j = 0; j < 4; ++j)
                gd.params[i][j] = (i < base_pslots.size()) ? base_pslots[i].dflt[j] : 0.0f;

        static_assert(lux::render::GraphMaterialData::kMaxTextures ==
                          lux::asset::MaterialData::kMaxTextures,
                      "graph texture-slot capacity must match across the asset/render boundary");
        for (std::uint32_t slot = 0;
             slot < lux::render::GraphMaterialData::kMaxTextures; ++slot)
        {
            const auto& tid = payload.texture_slot_ids[slot];
            if (tid.is_nil()) continue;
            auto tit = texture_resources_.find(tid);
            if (tit == texture_resources_.end() || tit->second.gpu_handle.is_null())
                continue;                       // unresolved/bad -> leave unbound
            gd.tex_bindless[slot] = tit->second.gpu_handle.index;
            gd.tex_mask |= (1u << slot);
        }

        e.upload_copy      = gd;
        e.upload_in_flight = true;
        // W3a render-state (passed by value, not borrowed): alpha_mode folds into
        // the graph bucket key, double_sided -> cull tier. alpha_cutoff is bake-only
        // (already a literal in payload's SPIR-V), so it is not forwarded.
        trackThen(material().uploadGraphMaterial(
            e.upload_copy, e.gbuffer_shader, e.forward_shader,
            static_cast<std::uint32_t>(payload.graph.render_state.alpha_mode),
            payload.graph.render_state.double_sided),
            [this, id](const lux::render::MaterialUploadedReply& r)
            {
                auto rit = graph_material_resources_.find(id);
                if (rit == graph_material_resources_.end()) return;
                rit->second.upload_in_flight = false;
                // A generic dispatch failure delivers a DEFAULT reply {status 0, null
                // handle} — validate the handle too, not just status, or the entry
                // settles as a ready-but-null material (P1-4).
                if (r.status == 0 && !r.handle.is_null())
                    rit->second.gpu_handle = r.handle;
                else
                {
                    rit->second.failed = true;
                    std::cerr << "[RenderableSystem] graph material upload failed "
                                 "(status=" << r.status << "); instance will not "
                                 "render\n";
                }
            });
        return {};
    }

    // ── ensureMaterialInstance ───────────────────────────────────────────
    // A material INSTANCE shares its parent graph material's shader/PSO and only
    // overrides params/textures (optionally render-state). It NEVER compiles or
    // re-bakes SPIR-V — it REUSES the parent's ShaderHandles, so its shader_key
    // matches the parent + every sibling => ONE shared bucket/PSO, while submitGraph
    // still gives this instance its OWN per-instance SSBO lane. Stages:
    //   (0) resolve the parent id from the instance payload
    //   (1) gate on ensureGraphMaterial(parent) — compiles the parent's shaders ONCE
    //   (2) resolve EFFECTIVE (parent ⊕ override) texture slots to bindless
    //   (3) build per-instance GraphMaterialData (parent params ⊕ overrides) + upload
    //       with the PARENT's ShaderHandles + the effective render-state.
    lux::render::RMaterialHandle
    RenderableBridgeContext::ensureMaterialInstance(const lux::asset::asset_id_t& id)
    {
        auto [it, inserted] = material_instance_resources_.try_emplace(id);
        auto& e = it->second;
        (void)inserted;

        if (!e.gpu_handle.is_null()) return e.gpu_handle;  // ready
        if (e.failed)                return {};            // known-bad, no retry

        const auto* inst_asset = mgr_->fetchAssetAs<lux::asset::MaterialInstanceAsset>(id);
        if (inst_asset == nullptr || inst_asset->data() == nullptr)
        {
            request_load_(id);
            return {};                                     // asset not loaded yet
        }
        const lux::asset::MaterialInstanceData& inst = *inst_asset->data();

        // ── Stage 0: resolve parent (set early so acquire/release can find it). ──
        e.parent_id = inst.parent_material_id;
        if (e.parent_id.is_nil())
        {
            e.failed = true;
            std::cerr << "[RenderableSystem] material instance has no parent; "
                         "instance will not render\n";
            return {};
        }

        // ── Stage 1: gate on the PARENT graph material. ensureGraphMaterial compiles
        //    its gbuffer/forward SPIR-V ONCE; the instance + all siblings reuse those
        //    deduped ShaderHandles -> identical shader_key -> shared bucket/PSO. ──
        (void)ensureGraphMaterial(e.parent_id);
        auto pit = graph_material_resources_.find(e.parent_id);
        if (pit == graph_material_resources_.end())
            return {};                                     // parent not a graph material / not seen yet
        const auto& parent = pit->second;
        if (parent.failed)
        {
            e.failed = true;
            std::cerr << "[RenderableSystem] material instance parent failed to bring "
                         "up; instance will not render\n";
            return {};
        }
        if (parent.gpu_handle.is_null())
            return {};                                     // parent still compiling/uploading
        const auto* parent_asset =
            mgr_->fetchAssetAs<lux::asset::MaterialAsset>(e.parent_id);
        if (parent_asset == nullptr || parent_asset->data() == nullptr)
            return {};                                     // parent data evicted — retry next frame
        const lux::asset::MaterialData& pp = *parent_asset->data();

        // ── Stage 2: resolve EFFECTIVE texture slots (parent ⊕ instance overrides). ──
        lux::asset::asset_id_t eff_tex[lux::asset::MaterialData::kMaxTextures];
        for (std::uint32_t s = 0; s < lux::asset::MaterialData::kMaxTextures; ++s)
            eff_tex[s] = (inst.tex_override_mask & (1u << s))
                             ? inst.texture_slot_ids[s]
                             : pp.texture_slot_ids[s];

        if (e.texture_ids.empty())
            for (const auto& tid : eff_tex)
                e.texture_ids.push_back(tid);

        bool all_settled = true;
        for (const auto& tid : eff_tex)
        {
            if (tid.is_nil()) continue;
            (void)ensureTexture(tid);
            auto tit = texture_resources_.find(tid);
            if (tit == texture_resources_.end()) { all_settled = false; continue; }
            if (tit->second.pending) all_settled = false;
        }
        if (!all_settled) return {};

        // ── Stage 3: build the per-instance GraphMaterialData (parent ⊕ overrides). ──
        if (e.upload_in_flight) return {};

        lux::render::GraphMaterialData gd{};
        // Parent param VALUES = parent graph's param-slot defaults (the SSOT);
        // the instance override mask replaces selected lanes.
        const auto& parent_pslots = pp.graph.param_slots;
        gd.param_count = static_cast<std::uint32_t>(
            parent_pslots.size() < lux::render::GraphMaterialData::kMaxParams
                ? parent_pslots.size() : lux::render::GraphMaterialData::kMaxParams);
        for (std::uint32_t i = 0; i < lux::render::GraphMaterialData::kMaxParams; ++i)
        {
            const bool ov = (inst.param_override_mask & (1u << i)) != 0u;
            for (std::uint32_t j = 0; j < 4; ++j)
                gd.params[i][j] = ov ? inst.params[i][j]
                                     : (i < parent_pslots.size() ? parent_pslots[i].dflt[j] : 0.0f);
        }
        for (std::uint32_t s = 0; s < lux::render::GraphMaterialData::kMaxTextures; ++s)
        {
            const auto& tid = eff_tex[s];
            if (tid.is_nil()) continue;
            auto tit = texture_resources_.find(tid);
            if (tit == texture_resources_.end() || tit->second.gpu_handle.is_null())
                continue;
            gd.tex_bindless[s] = tit->second.gpu_handle.index;
            gd.tex_mask |= (1u << s);
        }

        // Effective render-state: inherit parent's unless the instance overrides it
        // (overriding alpha_mode/double_sided puts the instance on its OWN PSO).
        const std::uint32_t eff_alpha_mode =
            inst.render_state_override ? inst.alpha_mode
                                       : static_cast<std::uint32_t>(pp.graph.render_state.alpha_mode);
        const bool eff_double_sided =
            inst.render_state_override ? inst.double_sided : pp.graph.render_state.double_sided;

        e.upload_copy      = gd;
        e.upload_in_flight = true;
        // Reuse the PARENT's ShaderHandles (NOT re-baked): identical shader_key ->
        // shared bucket/PSO; submitGraph still allocates this instance its OWN lane.
        trackThen(material().uploadGraphMaterial(
            e.upload_copy, parent.gbuffer_shader, parent.forward_shader,
            eff_alpha_mode, eff_double_sided),
            [this, id](const lux::render::MaterialUploadedReply& r)
            {
                auto rit = material_instance_resources_.find(id);
                if (rit == material_instance_resources_.end()) return;
                rit->second.upload_in_flight = false;
                // Validate the handle too, not just status: a dispatch-failure default
                // reply {status 0, null handle} must settle as failed, not a ready-but-null
                // zombie (the material-instance twin of the mesh/texture check).
                if (r.status == 0 && !r.handle.is_null())
                    rit->second.gpu_handle = r.handle;
                else
                {
                    rit->second.failed = true;
                    std::cerr << "[RenderableSystem] material instance upload failed "
                                 "(status=" << r.status << "); instance will not "
                                 "render\n";
                }
            });
        return {};
    }

    // (rewriteTextureBindings retired with the builtin material path — W5a. Graph
    // materials resolve texture-slot UUIDs to bindless directly in ensureGraphMaterial
    // / ensureMaterialInstance.)

    // ── acquire / release ──────────────────────────────────────────────

    void RenderableBridgeContext::acquireMesh(const lux::asset::asset_id_t& mesh_id)
    {
        if (mesh_id.is_nil()) return;
        auto it = mesh_resources_.find(mesh_id);
        if (it == mesh_resources_.end()) return;   // ensureMesh wasn't called
        ++it->second.refcount;
    }

    void RenderableBridgeContext::acquireMaterial(const lux::asset::asset_id_t& mat_id)
    {
        if (mat_id.is_nil()) return;
        // Graph materials live in their own cache (created by ensureGraphMaterial);
        // dispatch by map membership so the two caches stay disjoint.
        if (auto git = graph_material_resources_.find(mat_id);
            git != graph_material_resources_.end())
        {
            auto& e = git->second;
            if (e.refcount++ == 0)
                for (const auto& tex_id : e.texture_ids)
                    if (auto tit = texture_resources_.find(tex_id);
                        tit != texture_resources_.end())
                        ++tit->second.refcount;
            return;
        }
        // Material instances: bump the instance's effective-texture refs AND pin the
        // PARENT graph material (its shaders/PSO) for the instance's lifetime.
        if (auto iit = material_instance_resources_.find(mat_id);
            iit != material_instance_resources_.end())
        {
            auto& e = iit->second;
            if (e.refcount++ == 0)
            {
                for (const auto& tex_id : e.texture_ids)
                    if (auto tit = texture_resources_.find(tex_id);
                        tit != texture_resources_.end())
                        ++tit->second.refcount;
                acquireMaterial(e.parent_id);   // parent is a graph material (not an instance) — no recursion
            }
            return;
        }
        // No builtin material cache anymore (W5a) — only graph + instance materials.
    }

    void RenderableBridgeContext::releaseTexture(const lux::asset::asset_id_t& tex_id)
    {
        if (tex_id.is_nil()) return;
        auto it = texture_resources_.find(tex_id);
        if (it == texture_resources_.end() || it->second.refcount == 0) return;
        if (--it->second.refcount != 0) return;
        if (!it->second.gpu_handle.is_null())
            session_->destroyTexture(it->second.gpu_handle);
        texture_resources_.erase(it);
    }

    void RenderableBridgeContext::releaseMaterial(const lux::asset::asset_id_t& mat_id)
    {
        if (mat_id.is_nil()) return;

        // Graph materials: 1->0 cascade — release each held texture, destroy the GPU
        // material, AND destroy the compiled graph shader modules. The client now has a
        // destroyShader (P0-2), so the gbuffer/forward ShaderHandles are reclaimed via the
        // server's refcounted, content-deduped shader cache (freed on 1->0) instead of
        // leaking until renderer teardown — a base graph material compiles at least one.
        // (A material INSTANCE reuses the parent's shaders and must NOT destroy them; that
        // branch below stays shader-free.)
        if (auto git = graph_material_resources_.find(mat_id);
            git != graph_material_resources_.end())
        {
            auto& e = git->second;
            if (e.refcount == 0) return;
            if (--e.refcount != 0) return;
            auto texture_ids          = std::move(e.texture_ids);
            const auto gpu_handle     = e.gpu_handle;
            const auto gbuffer_shader = e.gbuffer_shader;
            const auto forward_shader = e.forward_shader;
            graph_material_resources_.erase(git);
            for (const auto& tex_id : texture_ids) releaseTexture(tex_id);
            if (!gpu_handle.is_null())     material().destroyMaterial(gpu_handle);
            if (!gbuffer_shader.is_null()) session_->destroyShader(gbuffer_shader);
            if (!forward_shader.is_null()) session_->destroyShader(forward_shader);
            return;
        }

        // Material instances: 1->0 cascade — release effective textures, release the
        // PARENT ref (symmetric with acquire; may reap the parent), destroy this
        // instance's own GPU material. The parent owns the shaders — never destroyed here.
        if (auto iit = material_instance_resources_.find(mat_id);
            iit != material_instance_resources_.end())
        {
            auto& e = iit->second;
            if (e.refcount == 0) return;
            if (--e.refcount != 0) return;
            auto texture_ids      = std::move(e.texture_ids);
            const auto parent_id  = e.parent_id;
            const auto gpu_handle = e.gpu_handle;
            material_instance_resources_.erase(iit);
            for (const auto& tex_id : texture_ids) releaseTexture(tex_id);
            releaseMaterial(parent_id);   // drop the parent ref (parent is a graph material)
            if (!gpu_handle.is_null())
                material().destroyMaterial(gpu_handle);
            return;
        }
        // No builtin material cache anymore (W5a) — only graph + instance materials.
    }

    void RenderableBridgeContext::releaseMesh(const lux::asset::asset_id_t& mesh_id)
    {
        if (mesh_id.is_nil()) return;
        auto it = mesh_resources_.find(mesh_id);
        if (it == mesh_resources_.end() || it->second.refcount == 0) return;
        if (--it->second.refcount != 0) return;
        if (!it->second.gpu_handle.is_null())
            meshStack().destroyMesh(it->second.gpu_handle);
        mesh_resources_.erase(it);
    }

    // ── Teardown drain (two-phase shutdown) ─────────────────────────────────────
    bool RenderableBridgeContext::hasInflightUploads() const noexcept
    {
        for (const auto& [id, e] : mesh_resources_)          if (e.pending) return true;
        for (const auto& [id, e] : texture_resources_)       if (e.pending) return true;
        for (const auto& [id, e] : graph_material_resources_)
            if (e.gbuffer_in_flight || e.forward_in_flight || e.upload_in_flight) return true;
        for (const auto& [id, e] : material_instance_resources_)
            if (e.upload_in_flight) return true;
        return false;
    }

    void RenderableBridgeContext::destroyUnreferencedResources()
    {
        // A never-acquired resource (uploaded during the teardown drain for an orphan
        // create we skipped acquiring, or whose instance was already torn down) sits at
        // refcount 0 with a live GPU handle. release*() only destroys on a 1->0 transition,
        // so it never fires here — destroy directly. Only touch SETTLED entries (a still-
        // inflight one is covered by the drain wait). A refcount-0 material was never
        // acquired, so it holds no texture refs -> no cascade needed.
        for (auto it = mesh_resources_.begin(); it != mesh_resources_.end(); )
        {
            const auto& e = it->second;
            if (!e.pending && e.refcount == 0 && !e.gpu_handle.is_null())
            { meshStack().destroyMesh(e.gpu_handle); it = mesh_resources_.erase(it); }
            else ++it;
        }
        for (auto it = texture_resources_.begin(); it != texture_resources_.end(); )
        {
            const auto& e = it->second;
            if (!e.pending && e.refcount == 0 && !e.gpu_handle.is_null())
            { session_->destroyTexture(e.gpu_handle); it = texture_resources_.erase(it); }
            else ++it;
        }
        for (auto it = graph_material_resources_.begin(); it != graph_material_resources_.end(); )
        {
            const auto& e = it->second;
            const bool settled = !e.gbuffer_in_flight && !e.forward_in_flight && !e.upload_in_flight;
            // A settled, never-acquired (refcount 0) entry is reclaimable — INCLUDING one
            // frozen MID-bring-up (gpu_handle null: after beginShutdown the drive phase is
            // rejected, so ensureGraphMaterial never advances it to terminal — P0-2). Destroy
            // whatever it actually produced: the GPU material if it finished, and the compiled
            // shader modules regardless of gpu_handle (they're the piece that would otherwise
            // leak). Its resolved textures sit at refcount 0 (a refcount-0 material never took
            // texture refs — acquireMaterial bumps them only on 0->1), so the texture loop
            // above already reclaimed them; no cascade needed here.
            if (settled && e.refcount == 0)
            {
                if (!e.gpu_handle.is_null())     material().destroyMaterial(e.gpu_handle);
                if (!e.gbuffer_shader.is_null()) session_->destroyShader(e.gbuffer_shader);
                if (!e.forward_shader.is_null()) session_->destroyShader(e.forward_shader);
                it = graph_material_resources_.erase(it);
            }
            else ++it;
        }
        for (auto it = material_instance_resources_.begin(); it != material_instance_resources_.end(); )
        {
            const auto& e = it->second;
            if (!e.upload_in_flight && e.refcount == 0 && !e.gpu_handle.is_null())
            { material().destroyMaterial(e.gpu_handle); it = material_instance_resources_.erase(it); }
            else ++it;
        }
    }

} // namespace lux::render_bridge
