add_subdirectory(description)
add_subdirectory(system)
add_subdirectory(composition)
add_subdirectory(asset)
add_subdirectory(integration/world_materialization)
add_subdirectory(integration/script_description)
add_subdirectory(scripting/assets)
add_subdirectory(scripting/skeleton)
if(TARGET simulation_script_lua)
    add_subdirectory(scripting/assets_lua)
endif()
add_subdirectory(integration/script)
add_subdirectory(builtin_systems/transform)
add_subdirectory(builtin_systems/mesh_query)
add_subdirectory(components/camera)
if(TARGET render_runtime)
    add_subdirectory(builtin_systems/render)
endif()

add_subdirectory(builtin_systems/world_loading)

add_subdirectory(plugins)
