add_subdirectory(description)
add_subdirectory(system)
add_subdirectory(meta)
add_subdirectory(composition)
add_subdirectory(asset)
add_subdirectory(integration/world_materialization)
add_subdirectory(integration/script_description)
add_subdirectory(integration/script)
add_subdirectory(builtin_systems/mesh_query)
add_subdirectory(builtin_systems/render)

add_subdirectory(builtin_systems/world_loading)
