add_subdirectory(desktop)
add_subdirectory(desktop/modules)
add_subdirectory(viewport)
add_subdirectory(widgets)
add_subdirectory(scene/interaction)
add_subdirectory(material/interaction)
add_subdirectory(flow/interaction)
add_subdirectory(project)
add_subdirectory(tasks)
add_subdirectory(scene)
add_subdirectory(material)
add_subdirectory(flow)
add_subdirectory(scene/contributions)
