cmake_minimum_required(VERSION 3.22)
project(lux_script_lua_values_consumer LANGUAGES CXX)
find_package(lux-cmake-toolset CONFIG REQUIRED)
find_package(lux-engine-function REQUIRED COMPONENTS script_core script_lua)
find_package(lux-engine-simulation REQUIRED COMPONENTS simulation_script_lua simulation_script simulation_description)
find_package(lux-engine-simulation-composition REQUIRED COMPONENTS simulation_composition)
include_component_cmake_scripts(lux::engine::function::script_core)
include_component_cmake_scripts(lux::engine::function::script_lua)
add_executable(lux_script_lua_values_consumer main.cpp Runtime.cpp)
target_compile_features(lux_script_lua_values_consumer PRIVATE cxx_std_20)
target_include_directories(lux_script_lua_values_consumer PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(lux_script_lua_values_consumer PRIVATE lux::engine::simulation::simulation_script_lua
    lux::engine::simulation::simulation_script lux::engine::simulation::composition
    lux::engine::function::script_lua_vm)
if(MSVC)
    target_compile_options(lux_script_lua_values_consumer PRIVATE /UNDEBUG)
else()
    target_compile_options(lux_script_lua_values_consumer PRIVATE -UNDEBUG)
endif()
lux_script_lua_values(TARGET lux_script_lua_values_consumer SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/Values.hpp
    RULE_HEADERS ${CMAKE_CURRENT_SOURCE_DIR}/Rules.hpp)
lux_script_abilities(TARGET lux_script_lua_values_consumer SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/Ability.hpp)
