if(NOT TARGET toolchain_shader_emitter)
    add_subdirectory(shader)
endif()
if(NOT TARGET toolchain_material_compiler)
    add_subdirectory(material)
endif()
if(NOT TARGET toolchain_texture_cooker)
    add_subdirectory(asset)
endif()
add_subdirectory(lua)
add_subdirectory(flowforge)
if(TARGET physics2d_simulation)
    add_subdirectory(physics2d)
endif()
