include_guard(GLOBAL)
if(NOT COMMAND lux_add_codegen_job)
    find_package(lux-cxx REQUIRED CONFIG COMPONENTS reflection_generator)
    include_component_cmake_scripts(lux::cxx::reflection_generator)
endif()
function(lux_script_lua_values)
    cmake_parse_arguments(ARGS "" "TARGET;OUTPUT_ROOT" "SOURCES;LOGICAL_PATHS;RULE_HEADERS;EXTRA_COMPILE_OPTIONS" ${ARGN})
    if(NOT ARGS_TARGET OR NOT TARGET ${ARGS_TARGET} OR NOT ARGS_SOURCES)
        message(FATAL_ERROR "lux_script_lua_values requires a target and explicit type headers")
    endif()
    if(NOT ARGS_LOGICAL_PATHS)
        foreach(source IN LISTS ARGS_SOURCES)
            get_filename_component(logical "${source}" NAME)
            list(APPEND ARGS_LOGICAL_PATHS "${logical}")
        endforeach()
    endif()
    if(NOT ARGS_OUTPUT_ROOT)
        set(ARGS_OUTPUT_ROOT "${CMAKE_CURRENT_BINARY_DIR}/generated/${ARGS_TARGET}/lua_values")
    endif()
    set(template_dir "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/template")
    set(rule_options)
    set(rule_json "[]")
    set(rule_index 0)
    foreach(header IN LISTS ARGS_RULE_HEADERS)
        get_filename_component(absolute "${header}" ABSOLUTE)
        file(TO_CMAKE_PATH "${absolute}" absolute)
        string(JSON rule_json SET "${rule_json}" ${rule_index} "\"${absolute}\"")
        math(EXPR rule_index "${rule_index}+1")
    endforeach()
    set(job ${ARGS_TARGET}_lua_values)
    lux_add_codegen_job(NAME ${job} MARKER luxlua TARGET_FILES ${ARGS_SOURCES} LOGICAL_PATHS ${ARGS_LOGICAL_PATHS}
        EXTRA_COMPILE_OPTIONS -D__LUX_PARSE_TIME__=1 ${ARGS_EXTRA_COMPILE_OPTIONS} DEPENDS ${ARGS_RULE_HEADERS})
    lux_codegen_add_validation(JOB ${job} NAME lua_value_shape TEMPLATE ${template_dir}/lua_value.validation.template)
    lux_codegen_add_projection(JOB ${job} NAME lua_value TEMPLATE ${template_dir}/lua_value.template
        OUTPUT_ROOT ${ARGS_OUTPUT_ROOT} OUTPUT_SUFFIX .lua.value.generated.hpp FLAT_OUTPUT
        JSON_FIELD "{\"rule_headers\":${rule_json}}")
    lux_target_add_codegen(TARGET ${ARGS_TARGET} JOB ${job} PROJECTIONS lua_value_shape lua_value DONT_ADD_TO_SOURCE)
    target_include_directories(${ARGS_TARGET} PUBLIC "$<BUILD_INTERFACE:${ARGS_OUTPUT_ROOT}>")
    set_target_properties(${ARGS_TARGET} PROPERTIES LUX_LUA_VALUE_GENERATED_DIR "${ARGS_OUTPUT_ROOT}")
endfunction()
