from pathlib import Path
p=Path(r"E:/SyncForder/CodeRepos/lux-engine-p12/editor/tests/integration/application/application.cpp")
s=p.read_text()
needle='    assert(app->requestExit());\n    const auto deadline ='
assert needle in s
s=s.replace(needle, '    // Accepted source encoding and real material compilation remain owned while the Run/GPU are live.\n    const auto exit_content = impl.sessions_.describe(material_id)->current;\n    auto exit_save = impl.save({material_id, exit_content}, persistence::ESaveMode::SAVE);\n    assert(exit_save && impl.saves_.status(*exit_save)->stage != persistence::ESaveStage::TERMINAL);\n    lux::editor::material::MaterialCompileId exit_compile;\n    auto compile_at_exit = [&](ui::Pane& pane) {\n        auto compiled = static_cast<lux::editor::material::MaterialView&>(pane).compile();\n        assert(compiled);\n        exit_compile = *compiled;\n    };\n    assert(impl.desktop_->views().withView(*shown_again, compile_at_exit));\n    auto exit_operation = impl.material_compilation_.operation(exit_compile);\n    assert(exit_operation && !exit_operation->get().ready());\n    const auto exit_task = exit_operation->get().task();\n    assert(impl.runs_.info(run) && !impl.engine_->renderContext()->resources().empty());\n    assert(app->requestExit());\n    const auto deadline =')
needle='    assert(!impl.desktop_ && impl.engine_->renderContext()->resources().empty());'
s=s.replace(needle, needle+'\n    assert(impl.material_compilation_.snapshotIds()->empty());\n    assert(!impl.material_compilation_.operation(exit_compile));\n    const auto exit_completed = impl.engine_->execution().taskInfo(exit_task);\n    assert(exit_completed && exit_completed->finished && exit_completed->state == process::ETaskState::SUCCEEDED);\n    const auto exit_saved = std::ranges::find(impl.save_reports_, *exit_save,\n        &std::remove_reference_t<decltype(impl)>::SavePresentation::id);\n    assert(exit_saved != impl.save_reports_.end() && exit_saved->result);\n    assert(std::holds_alternative<persistence::CommitReceipt>(*exit_saved->result));\n    assert(impl.pending_saves_.empty() && impl.sessions_.size() == 0);\n    std::cout << "X12-09: accepted encode/compile, independent Run and GPU drain; source publication retained\\n";')
p.write_text(s)
