execute_process(COMMAND "${CMAKE_COMMAND}" --build "${BUILD_DIR}" --target "${PROBE}" -j 4 -- -k 0
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${BUILD_DIR}/${PROBE}.log" "${output}\n${error}")
if(result EQUAL 0)
    message(FATAL_ERROR "Illegal script ownership/authority compiled: ${PROBE}")
endif()
if(PROBE MATCHES "NONTRIVIAL")
    set(expected "invokeScriptAbilityAsync")
else()
    set(expected "private|inaccessible")
endif()
if(NOT "${output}\n${error}" MATCHES "${expected}")
    message(FATAL_ERROR "Unrelated compilation failure: ${output}\n${error}")
endif()
if("${output}\n${error}" MATCHES "C1083|file not found|No such file or directory|cannot open include")
    message(FATAL_ERROR "Missing SDK dependency is not a contract rejection")
endif()
