#pragma once

#include <cstdint>
#include <filesystem>
#include <memory>
#include <string>

#include <lux/engine/resource/asset/TextureCodec.hpp>
#include <lux/engine/description/Texture.hpp>

namespace lux::toolchain
{
    struct TextureImportConfig
    {
        bool flip_vertically{false};
        bool force_alpha{true};
        lux::rdesc::ETexturePixelFormat output_format{
            lux::rdesc::ETexturePixelFormat::RGBA8_SRGB
        };
        lux::rdesc::ETextureColorSpace color_space{
            lux::rdesc::ETextureColorSpace::SRGB
        };
        std::uint32_t flags{
            lux::rdesc::toUnderlying(
                lux::rdesc::ETextureAssetFlags::NONE
            )
        };

        /// Stable seed for deterministic sub-assets generated by an importer.
        /// Empty selects the AssetManager's normal random-id path.
        std::string deterministic_seed;
    };

    /// Authoring image decoder and texture cooker. Runtime code must use
    /// asset::TextureCodec, which only understands cooked .luxasset payloads.
    class TextureImporter final : public lux::asset::TextureCodec
    {
    public:
        explicit TextureImporter(
            std::shared_ptr<lux::asset::AssetManager> manager
        );
        ~TextureImporter() override;

        [[nodiscard]] TextureImportConfig& config() noexcept
        {
            return config_;
        }

        [[nodiscard]] const TextureImportConfig& config() const noexcept
        {
            return config_;
        }

        [[nodiscard]] lux::cxx::expected<
            lux::asset::AssetIDPair,
            lux::asset::EAssetError
        > importFromFile(
            const std::filesystem::path& external_path
        ) override;

        [[nodiscard]] lux::cxx::expected<
            std::unique_ptr<lux::asset::LuxAsset>,
            lux::asset::EAssetError
        > fromMemory(const void* memory, std::size_t length) override;

    private:
        TextureImportConfig config_{};
    };
} // namespace lux::toolchain
