include_guard(GLOBAL)

# V4 migration checks only. The model and rules live in source, never in dev_log/.internal.
function(lux_editor_collect_targets directory output)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        lux_editor_collect_targets("${child}" nested)
        list(APPEND targets ${nested})
    endforeach()
    set(${output} "${targets}" PARENT_SCOPE)
endfunction()

function(lux_editor_json value output)
    string(REPLACE "\\" "/" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(lux_editor_check_architecture)
    find_package(Python3 REQUIRED COMPONENTS Interpreter)
    include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/EditorTests.cmake")
    # identity's directory-local imported UUID target is otherwise invisible here.
    # Read the same already-selected package in this inspection scope; never infer an
    # unknown leaf or search for a different package to make a boundary check pass.
    if(TARGET identity AND NOT TARGET stduuid)
        if(NOT IS_DIRECTORY "${stduuid_DIR}")
            message(FATAL_ERROR "Cannot inspect identity: selected stduuid package is unavailable")
        endif()
        find_package(stduuid CONFIG REQUIRED PATHS "${stduuid_DIR}" NO_DEFAULT_PATH)
    endif()
    # These packages were selected by the CPU schema/process subdirectories. Inspect their actual
    # imported interfaces from the root too; an unseen imported edge must never be treated as a leaf.
    if(TARGET schema)
        foreach(package Eigen3 EnTT)
            if(NOT IS_DIRECTORY "${${package}_DIR}")
                message(FATAL_ERROR "Cannot inspect schema: selected ${package} package is unavailable")
            endif()
            find_package(${package} CONFIG REQUIRED PATHS "${${package}_DIR}" NO_DEFAULT_PATH)
        endforeach()
    endif()
    if(TARGET process_execution AND NOT TARGET Threads::Threads)
        find_package(Threads REQUIRED)
    endif()
    if(TARGET render_vulkan)
        find_package(Vulkan REQUIRED)
        find_package(VulkanMemoryAllocator CONFIG REQUIRED PATHS "${VulkanMemoryAllocator_DIR}" NO_DEFAULT_PATH)
    endif()
    if(TARGET window)
        foreach(package glfw3 nfd)
            if(NOT IS_DIRECTORY "${${package}_DIR}")
                message(FATAL_ERROR "Cannot inspect window: selected ${package} package is unavailable")
            endif()
            find_package(${package} CONFIG REQUIRED PATHS "${${package}_DIR}" NO_DEFAULT_PATH)
        endforeach()
    endif()
    # P07 inspects the actual renderer/toolchain static closure. Imported targets selected
    # in child scopes must be visible here; unresolved target names are never native leaves.
    if(TARGET render_features)
        foreach(package assimp meshoptimizer spirv_cross_core)
            find_package(${package} CONFIG REQUIRED PATHS "${${package}_DIR}" NO_DEFAULT_PATH)
        endforeach()
    endif()
    if(TARGET flowforge_compiler)
        find_package(LLVM CONFIG REQUIRED PATHS "${LLVM_DIR}" NO_DEFAULT_PATH)
        find_package(MLIR CONFIG REQUIRED PATHS "${MLIR_DIR}" NO_DEFAULT_PATH)
    endif()
    if(TARGET editor_widgets AND nlohmann_json_DIR)
        find_package(nlohmann_json CONFIG REQUIRED PATHS "${nlohmann_json_DIR}" NO_DEFAULT_PATH)
    endif()
    lux_editor_collect_targets("${PROJECT_SOURCE_DIR}" targets)
    set(records "")
    set(visited "")
    while(targets)
        list(POP_FRONT targets target)
        if(target IN_LIST visited)
            continue()
        endif()
        list(APPEND visited "${target}")
        set(record "{\"name\":\"${target}\"")
        foreach(property SOURCE_DIR TYPE IMPORTED SOURCES INTERFACE_SOURCES INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES
                         LINK_LIBRARIES INTERFACE_LINK_LIBRARIES MANUALLY_ADDED_DEPENDENCIES)
            get_target_property(value ${target} ${property})
            if(value STREQUAL "value-NOTFOUND")
                set(value "")
            endif()
            lux_editor_json("${value}" encoded)
            string(APPEND record ",\"${property}\":${encoded}")
        endforeach()
        set(edges "")
        # Conservative union for conditional links. Alias resolution is done by CMake,
        # including LINK_ONLY/static edges; generator dependencies are kept separately.
        foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES MANUALLY_ADDED_DEPENDENCIES)
            get_target_property(raw ${target} ${property})
            if(raw STREQUAL "raw-NOTFOUND")
                continue()
            endif()
            string(REGEX REPLACE "::@\\([^)]*\\)|::@" "" raw "${raw}")
            # Keep a full imported native library path as one edge, including spaces. Its
            # original value remains in the property record; only the identity is portable.
            foreach(item IN LISTS raw)
                if(IS_ABSOLUTE "${item}")
                    if(NOT EXISTS "${item}")
                        message(FATAL_ERROR "Dependency inspection: missing native library ${item}")
                    endif()
                    get_filename_component(native_name "${item}" NAME)
                    string(REPLACE "${item}" "${native_name}" raw "${raw}")
                endif()
            endforeach()
            string(REGEX REPLACE "-delayload:[A-Za-z0-9_.-]+" "" raw "${raw}")
            # Conditions are selectors, not link names; keep both branches' actual links.
            string(REGEX REPLACE "\\$<(CONFIG|PLATFORM_ID|CXX_COMPILER_ID|BOOL|LINK_LANGUAGE):[^>]*>" "" raw "${raw}")
            string(REGEX REPLACE "::@\\([^)]*\\)|::@" "" raw "${raw}")
            string(REGEX REPLACE "\\$<[A-Za-z0-9_]+:" ";" raw "${raw}")
            string(REGEX MATCHALL "[A-Za-z0-9_][A-Za-z0-9_:.+-]*" candidates "${raw}")
            foreach(candidate IN LISTS candidates)
                if(candidate MATCHES "^(debug|optimized|general)$")
                    continue()
                endif()
                if(TARGET "${candidate}")
                    get_target_property(alias "${candidate}" ALIASED_TARGET)
                    if(alias)
                        set(candidate "${alias}")
                    endif()
                    list(APPEND targets "${candidate}")
                endif()
                # Also retain unresolved names. Foundation checks must fail closed.
                list(APPEND edges "${property}:${candidate}")
            endforeach()
        endforeach()
        list(REMOVE_DUPLICATES edges)
        lux_editor_json("${edges}" encoded)
        string(APPEND record ",\"edges\":${encoded}}")
        if(records)
            string(APPEND records ",\n")
        endif()
        string(APPEND records "${record}")
    endwhile()
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/editor-architecture")
    set(graph "${CMAKE_BINARY_DIR}/editor-architecture/targets.json")
    file(WRITE "${graph}" "[\n${records}\n]\n")
    execute_process(COMMAND "${Python3_EXECUTABLE}"
        "${PROJECT_SOURCE_DIR}/editor/tests/architecture/check_editor_boundaries.py"
        --repo "${PROJECT_SOURCE_DIR}" --graph "${graph}" --stage "${LUX_EDITOR_MIGRATION_STAGE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE report ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Editor migration boundary check failed:\n${report}${error}")
    endif()
endfunction()
