include_guard(GLOBAL)

# V4 migration checks only. The model and rules live in source, never in dev_log/.internal.
function(lux_editor_collect_targets directory output)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        lux_editor_collect_targets("${child}" nested)
        list(APPEND targets ${nested})
    endforeach()
    set(${output} "${targets}" PARENT_SCOPE)
endfunction()

function(lux_editor_json value output)
    string(REPLACE "\\" "/" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(lux_editor_check_architecture)
    find_package(Python3 REQUIRED COMPONENTS Interpreter)
    set(LUX_EDITOR_MIGRATION_STAGE P01 CACHE STRING "Current V4 Editor migration gate (P00..P13)")
    lux_editor_collect_targets("${PROJECT_SOURCE_DIR}" targets)
    set(records "")
    foreach(target IN LISTS targets)
        set(record "{\"name\":\"${target}\"")
        foreach(property SOURCE_DIR TYPE SOURCES INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES
                         LINK_LIBRARIES INTERFACE_LINK_LIBRARIES MANUALLY_ADDED_DEPENDENCIES)
            get_target_property(value ${target} ${property})
            if(value STREQUAL "value-NOTFOUND")
                set(value "")
            endif()
            lux_editor_json("${value}" encoded)
            string(APPEND record ",\"${property}\":${encoded}")
        endforeach()
        set(edges "")
        # Conservative union for conditional links. Alias resolution is done by CMake,
        # including LINK_ONLY/static edges; generator dependencies are kept separately.
        foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES MANUALLY_ADDED_DEPENDENCIES)
            get_target_property(raw ${target} ${property})
            string(REGEX REPLACE "\\$<[A-Za-z0-9_]+:" ";" raw "${raw}")
            string(REGEX MATCHALL "[A-Za-z0-9_][A-Za-z0-9_:.+-]*" candidates "${raw}")
            foreach(candidate IN LISTS candidates)
                if(TARGET "${candidate}")
                    get_target_property(alias "${candidate}" ALIASED_TARGET)
                    if(alias)
                        set(candidate "${alias}")
                    endif()
                    list(APPEND edges "${property}:${candidate}")
                endif()
            endforeach()
        endforeach()
        list(REMOVE_DUPLICATES edges)
        lux_editor_json("${edges}" encoded)
        string(APPEND record ",\"edges\":${encoded}}")
        if(records)
            string(APPEND records ",\n")
        endif()
        string(APPEND records "${record}")
    endforeach()
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/editor-architecture")
    set(graph "${CMAKE_BINARY_DIR}/editor-architecture/targets.json")
    file(WRITE "${graph}" "[\n${records}\n]\n")
    execute_process(COMMAND "${Python3_EXECUTABLE}"
        "${PROJECT_SOURCE_DIR}/editor/tests/architecture/check_editor_boundaries.py"
        --repo "${PROJECT_SOURCE_DIR}" --graph "${graph}" --stage "${LUX_EDITOR_MIGRATION_STAGE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE report ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Editor migration boundary check failed:\n${report}${error}")
    endif()
endfunction()
