include_guard(GLOBAL)
include(CMakeDependentOption)
# Test requirements, not product feature switches. Multiple requirements are conjunctive.
foreach(group NATIVE DESKTOP GPU TOOLCHAIN INSTALLED)
    if(group STREQUAL "NATIVE")
        set(default ON)
    else()
        set(default OFF)
    endif()
    cmake_dependent_option(LUX_EDITOR_BUILD_${group}_TESTS
        "Build Editor ${group} tests" ${default} "BUILD_TESTING" OFF)
endforeach()

set(LUX_EDITOR_TEST_DESKTOP_GPU OFF)
if(LUX_EDITOR_BUILD_DESKTOP_TESTS AND LUX_EDITOR_BUILD_GPU_TESTS)
    set(LUX_EDITOR_TEST_DESKTOP_GPU ON)
endif()
set(LUX_EDITOR_TEST_INSTALLED_UI OFF)
if(LUX_EDITOR_TEST_DESKTOP_GPU AND LUX_EDITOR_BUILD_INSTALLED_TESTS)
    set(LUX_EDITOR_TEST_INSTALLED_UI ON)
endif()

# These helpers are deliberately limited to the current migration's test targets.
function(lux_editor_test_options target)
    target_include_directories(${target} PRIVATE "${PROJECT_SOURCE_DIR}/cmake/test-support")
    if(MSVC)
        target_compile_options(${target} PRIVATE /UNDEBUG /utf-8)
    else()
        target_compile_options(${target} PRIVATE -UNDEBUG)
    endif()
endfunction()

# Linker flavor must match the target object format. AOT additionally verifies the actual bytes/triple.
function(lux_editor_find_linker output)
    if(WIN32)
        find_program(${output} NAMES lld-link REQUIRED)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        find_program(${output} NAMES ld.lld ld REQUIRED)
    else()
        message(FATAL_ERROR "Flow AOT tests do not support target ${CMAKE_SYSTEM_NAME}")
    endif()
    set(${output} "${${output}}" PARENT_SCOPE)
endfunction()
