include_guard(GLOBAL)

# Apply only to actual first-party compilation units, never to imported or
# dependency targets. Call once after the complete product has been composed.
function(lux_disable_rtti directory)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(target IN LISTS targets)
        get_target_property(kind "${target}" TYPE)
        if(kind STREQUAL "INTERFACE_LIBRARY" OR kind STREQUAL "UTILITY")
            continue()
        endif()
        get_target_property(source "${target}" SOURCE_DIR)
        cmake_path(IS_PREFIX PROJECT_SOURCE_DIR "${source}" NORMALIZE first_party)
        if(NOT first_party OR source MATCHES "/(third_party|_deps)/")
            continue()
        endif()
        if(MSVC)
            target_compile_options("${target}" PRIVATE /GR- /we4541)
        else()
            target_compile_options("${target}" PRIVATE -fno-rtti)
        endif()
        set_property(GLOBAL APPEND PROPERTY LUX_NO_RTTI_TARGETS "${target}")
    endforeach()
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        lux_disable_rtti("${child}")
    endforeach()
endfunction()
