cmake_minimum_required(VERSION 3.22)
include("${CMAKE_CURRENT_LIST_DIR}/ValidatePackageNesting.cmake")
if(DEFINED LUX_NESTING_PROBE)
    lux_validate_package_nesting("${LUX_TEST_ROOT}" "${LUX_TEST_ROOT}/${LUX_PARENT}" "${LUX_TEST_ROOT}/${LUX_CHILD}")
    return()
endif()
if(NOT DEFINED LUX_TEST_ROOT)
    message(FATAL_ERROR "LUX_TEST_ROOT is required")
endif()
file(MAKE_DIRECTORY "${LUX_TEST_ROOT}/engine/editor/application/tooling" "${LUX_TEST_ROOT}/engine/editor/ui/scene")
file(WRITE "${LUX_TEST_ROOT}/engine/editor/CMakeLists.txt"
    "add_subdirectory(application/tooling)\nadd_subdirectory(ui/scene)\n")
foreach(parent application ui)
    file(WRITE "${LUX_TEST_ROOT}/engine/editor/${parent}/CMakeLists.txt" "add_library(editor_${parent} STATIC source.cpp)\n")
endforeach()
function(probe name parent child expected_error)
    execute_process(COMMAND "${CMAKE_COMMAND}" -DLUX_NESTING_PROBE=ON
        "-DLUX_TEST_ROOT=${LUX_TEST_ROOT}" "-DLUX_PARENT=${parent}" "-DLUX_CHILD=${child}"
        -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expected_error STREQUAL "")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${name}: unexpected rejection: ${error}")
        endif()
    elseif(result EQUAL 0 OR NOT error MATCHES "${expected_error}")
        message(FATAL_ERROR "${name}: expected ${expected_error}, got exit=${result}: ${error}")
    endif()
    message(STATUS "${name}: PASS")
endfunction()
probe(tooling engine/editor/application engine/editor/application/tooling "")
probe(scene_ui engine/editor/ui engine/editor/ui/scene "")
probe(unlisted_child engine/editor/application engine/editor/application/unlisted "also aggregates")
file(APPEND "${LUX_TEST_ROOT}/engine/editor/application/CMakeLists.txt" "add_subdirectory(tooling)\n")
probe(parent_aggregation engine/editor/application engine/editor/application/tooling "enclosing package may not")
file(WRITE "${LUX_TEST_ROOT}/engine/editor/ui/CMakeLists.txt" "add_library(editor_ui STATIC source.cpp)\n")
file(WRITE "${LUX_TEST_ROOT}/engine/editor/CMakeLists.txt" "add_subdirectory(application/tooling)\n")
probe(missing_collection_owner engine/editor/ui engine/editor/ui/scene "Editor collection must configure")
