if(NOT DEFINED LUX_SOURCE_DIR)
    message(FATAL_ERROR "ER1_BOUNDARY: LUX_SOURCE_DIR is required")
endif()

function(lux_check_er1_source role path)
    file(READ "${path}" source)
    string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"\r\n]+[>\"]" includes "${source}")
    foreach(include IN LISTS includes)
        if(include MATCHES "lux/engine/editor/(context/|scene/|inspector/|EditorContext|EditorSelection|EditHistoryController)")
            message(FATAL_ERROR "ER1_BOUNDARY: ${role} includes retired Editor dependency: ${path}: ${include}")
        endif()
        if(role STREQUAL "editing" AND include MATCHES "lux/engine/(scene|ui|object|render|simulation|process|description|resource)/")
            message(FATAL_ERROR "ER1_BOUNDARY: editing includes business or UI dependency: ${path}: ${include}")
        endif()
        if(role STREQUAL "ui" AND include MATCHES "lux/engine/(scene/|simulation/|editor/sessions/|editor/rendering/)")
            message(FATAL_ERROR "ER1_BOUNDARY: generic UI includes business dependency: ${path}: ${include}")
        endif()
        if(role STREQUAL "sessions" AND include MATCHES "lux/engine/(ui/|window/|editor/ui/)|[<\"](imgui|GLFW|vulkan)")
            message(FATAL_ERROR "ER1_BOUNDARY: Session includes UI or backend dependency: ${path}: ${include}")
        endif()
        if(role STREQUAL "rendering" AND include MATCHES "lux/engine/editor/(ui/|sessions/|editing/)")
            message(FATAL_ERROR "ER1_BOUNDARY: Renderer includes Session or Editor UI dependency: ${path}: ${include}")
        endif()
        if(path MATCHES "/include/" AND include MATCHES "[<\"](imgui|GLFW|vulkan)|lux/engine/render/")
            message(FATAL_ERROR "ER1_BOUNDARY: public Editor API leaks a backend header: ${path}: ${include}")
        endif()
    endforeach()
endfunction()

if(DEFINED LUX_ER1_PROBE_FILE)
    lux_check_er1_source("${LUX_ER1_PROBE_ROLE}" "${LUX_ER1_PROBE_FILE}")
    return()
endif()

set(er1_sources_checked 0)
foreach(role editing ui rendering sessions)
    file(GLOB_RECURSE sources LIST_DIRECTORIES false
        "${LUX_SOURCE_DIR}/engine/editor/${role}/*.hpp"
        "${LUX_SOURCE_DIR}/engine/editor/${role}/*.cpp")
    foreach(path IN LISTS sources)
        if(path MATCHES "/test/|/test_support/|/ui/scene/")
            continue()
        endif()
        lux_check_er1_source("${role}" "${path}")
        math(EXPR er1_sources_checked "${er1_sources_checked} + 1")
    endforeach()
endforeach()
foreach(path application/src/Application.cpp application/sinclude/lux/engine/editor/application/Application.hpp)
    lux_check_er1_source(application "${LUX_SOURCE_DIR}/engine/editor/${path}")
endforeach()
file(GLOB_RECURSE scene_ui_sources LIST_DIRECTORIES false
    "${LUX_SOURCE_DIR}/engine/editor/ui/scene/src/*.cpp"
    "${LUX_SOURCE_DIR}/engine/editor/ui/scene/include/*.hpp"
    "${LUX_SOURCE_DIR}/engine/editor/ui/scene/pinclude/*.hpp")
foreach(path IN LISTS scene_ui_sources)
    lux_check_er1_source(scene_ui "${path}")
endforeach()
message(STATUS "ER-1 responsibility check passed (${er1_sources_checked} generic/core source files plus Scene UI and Application)")

file(READ "${LUX_SOURCE_DIR}/engine/editor/application/CMakeLists.txt" application_target)
if(application_target MATCHES "editor_context|editor_inspector|editor_scene[) ]")
    message(FATAL_ERROR "ER1_BOUNDARY: production Application links the historical editor stack")
endif()
