cmake_minimum_required(VERSION 3.22)
if(NOT DEFINED LUX_SOURCE_DIR)
    message(FATAL_ERROR "LUX_SOURCE_DIR is required")
endif()
set(core "${LUX_SOURCE_DIR}/engine/editor/editing")
file(GLOB_RECURSE files "${core}/include/*.hpp" "${core}/pinclude/*.hpp" "${core}/src/*.cpp")
foreach(path IN LISTS files)
    file(STRINGS "${path}" includes REGEX "^[ \t]*#[ \t]*include")
    foreach(line IN LISTS includes)
        if(line MATCHES "lux/" AND NOT line MATCHES "lux/(cxx/compile_time/|engine/editor/editing/)")
            message(FATAL_ERROR "Editing core has a forbidden dependency: ${path}: ${line}")
        endif()
    endforeach()
    file(READ "${path}" content)
    if(content MATCHES "lux::(scene|world|simulation|ui|object|graph|material|flowforge|process|render)::")
        message(FATAL_ERROR "Editing core contains business/UI vocabulary: ${path}")
    endif()
endforeach()
file(READ "${core}/CMakeLists.txt" cmake_content)
if(NOT cmake_content MATCHES "target_link_libraries\\(editor_editing PUBLIC lux::cxx::compile_time\\)")
    message(FATAL_ERROR "Editing core link contract changed; review its complete dependency closure")
endif()
message(STATUS "Editor Editing source and declared dependency boundary passed")
