include_guard(GLOBAL)

# A module declares its own exported declaration source. Products select targets, not C++ symbols.
function(engine_declare_editor_module)
    cmake_parse_arguments(ARG "" "TARGET;HEADER;LOGICAL_PATH;SOURCE_FILE" "" ${ARGN})
    foreach(required TARGET HEADER LOGICAL_PATH SOURCE_FILE)
        if(NOT ARG_${required})
            message(FATAL_ERROR "Editor module declaration requires ${required}")
        endif()
    endforeach()
    if(NOT TARGET ${ARG_TARGET})
        message(FATAL_ERROR "Unknown Editor module target: ${ARG_TARGET}")
    endif()
    foreach(key HEADER LOGICAL_PATH SOURCE_FILE)
        set_property(TARGET ${ARG_TARGET} PROPERTY LUX_EDITOR_MODULE_${key} "${ARG_${key}}")
    endforeach()
endfunction()

function(engine_target_add_editor_modules)
    cmake_parse_arguments(ARG "" "TARGET;NAME;NAMESPACE;OUTPUT_ROOT" "MODULES" ${ARGN})
    foreach(required TARGET NAME NAMESPACE)
        if(NOT ARG_${required})
            message(FATAL_ERROR "Editor module index requires ${required}")
        endif()
    endforeach()
    if(EXISTS "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../codegen/GenerateModules.cmake")
        set(generator_dir "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../codegen")
    else()
        set(generator_dir "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/codegen")
    endif()
    if(TARGET lux_editor_module_generator)
        set(generator "$<TARGET_FILE:lux_editor_module_generator>")
    else()
        get_filename_component(sdk_prefix "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../../.." ABSOLUTE)
        find_program(LUX_EDITOR_MODULE_GENERATOR_EXECUTABLE NAMES lux_editor_module_generator
            HINTS "${sdk_prefix}/bin" REQUIRED NO_DEFAULT_PATH)
        set(generator "${LUX_EDITOR_MODULE_GENERATOR_EXECUTABLE}")
    endif()
    if(NOT ARG_OUTPUT_ROOT)
        set(ARG_OUTPUT_ROOT "${CMAKE_CURRENT_BINARY_DIR}/module_gen/${ARG_NAME}")
    endif()
    set(inputs "")
    set(separator "")
    set(dependencies "")
    set(seen "")
    foreach(module IN LISTS ARG_MODULES)
        if(NOT TARGET ${module} OR module IN_LIST seen)
            message(FATAL_ERROR "Unknown or duplicate Editor module target: ${module}")
        endif()
        list(APPEND seen "${module}")
        foreach(key HEADER LOGICAL_PATH SOURCE_FILE)
            get_target_property(${key} ${module} LUX_EDITOR_MODULE_${key})
            if(NOT ${key})
                message(FATAL_ERROR "Target ${module} does not declare ${key}")
            endif()
        endforeach()
        set(job "${ARG_TARGET}_${ARG_NAME}_${module}")
        set(ir_root "${CMAKE_CURRENT_BINARY_DIR}/module_ir/${job}")
        lux_add_codegen_job(NAME ${job} MARKER luxmodule SOURCE_FILE "${SOURCE_FILE}" PARSE_INCLUDED_MARKED
            TARGET_FILES "${HEADER}" LOGICAL_PATHS "${LOGICAL_PATH}")
        lux_codegen_add_projection(JOB ${job} NAME module_ir TEMPLATE "${generator_dir}/ir.template"
            OUTPUT_ROOT "${ir_root}" OUTPUT_SUFFIX .module-ir SERIAL_META)
        lux_target_add_codegen(TARGET ${module} JOB ${job} DONT_ADD_TO_SOURCE DONT_INCLUDE)
        get_filename_component(directory "${LOGICAL_PATH}" DIRECTORY)
        get_filename_component(stem "${LOGICAL_PATH}" NAME_WE)
        set(ir "${ir_root}/${directory}/${stem}.module-ir.json")
        _meta_json_escape(json_ir "${ir}")
        _meta_json_escape(json_header "${LOGICAL_PATH}")
        string(APPEND inputs "${separator}{\"logical_path\":\"${json_header}\",\"ir\":\"${json_ir}\"}")
        set(separator ",")
        list(APPEND dependencies "${ir}")
        target_link_libraries(${ARG_TARGET} PRIVATE ${module})
    endforeach()
    foreach(key NAME NAMESPACE)
        _meta_json_escape(json_${key} "${ARG_${key}}")
    endforeach()
    set(config "${CMAKE_CURRENT_BINARY_DIR}/lux_codegen/${ARG_NAME}.modules.json")
    file(GENERATE OUTPUT "${config}" CONTENT
        "{\"name\":\"${json_NAME}\",\"namespace\":\"${json_NAMESPACE}\",\"inputs\":[${inputs}]}\n")
    set(outputs "${ARG_OUTPUT_ROOT}/${ARG_NAME}.modules.hpp" "${ARG_OUTPUT_ROOT}/${ARG_NAME}.modules.cpp")
    add_custom_command(OUTPUT ${outputs} "${ARG_OUTPUT_ROOT}/modules.complete"
        COMMAND ${CMAKE_COMMAND} "-DGENERATOR=${generator}" "-DCONFIG=${config}"
            "-DTEMPLATES=${generator_dir}/templates" "-DOUTPUT_ROOT=${ARG_OUTPUT_ROOT}" "-DNAME=${ARG_NAME}"
            -P "${generator_dir}/GenerateModules.cmake"
        DEPENDS ${dependencies} "${config}" "${generator}" "${generator_dir}/GenerateModules.cmake"
            "${generator_dir}/templates/declarations.template" "${generator_dir}/templates/index.template"
        BYPRODUCTS "${ARG_OUTPUT_ROOT}/staging/semantics.json"
            "${ARG_OUTPUT_ROOT}/staging/${ARG_NAME}.modules.hpp" "${ARG_OUTPUT_ROOT}/staging/${ARG_NAME}.modules.cpp"
        COMMENT "Generate selected Editor module strong references: ${ARG_NAME}" VERBATIM)
    target_sources(${ARG_TARGET} PRIVATE ${outputs})
    target_include_directories(${ARG_TARGET} PRIVATE "${ARG_OUTPUT_ROOT}")
endfunction()
