"""Bounded SDK codegen qualification. Only the isolated fixture and copied installed templates are modified."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import time

parser = argparse.ArgumentParser()
parser.add_argument('--sdk', required=True, type=Path)
parser.add_argument('--work', required=True, type=Path)
parser.add_argument('--cmake-arg', action='append', default=[])
args = parser.parse_args()
sdk, work = args.sdk.resolve(), args.work.resolve()
assert not work.exists(), 'Keep each qualification run and its failures'
work.mkdir(parents=True)
source, build, tools = work/'源码 空格', work/'build', work/'installed-tools'
shutil.copytree(Path(__file__).parent, source, ignore=shutil.ignore_patterns('__pycache__'))
scripts = Path('share/lux-engine-editor-scene-ui/scene_ui/cmake_scripts')
shutil.copytree(sdk/scripts, tools/scripts)
codegen = tools/scripts/'codegen'
module = tools/scripts/'engine_editor_imgui_inspector_codegen.cmake'
generator = sdk/'bin/lux_inspector_generator.exe' if os.name == 'nt' else sdk/'bin/lux_inspector_generator'
config = ['cmake', '-S', str(source), '-B', str(build), '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=RelWithDebInfo',
          f'-DCMAKE_PREFIX_PATH={sdk}', f'-DINSPECTOR_CMAKE_MODULE={module}',
          f'-DLUX_INSPECTOR_GENERATOR_EXECUTABLE={generator}', *args.cmake_arg]
events = []

def run(label, command, success=True):
    start = time.perf_counter()
    result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    data = result.stdout.decode('utf-8', errors='replace')
    (work/(label+'.log')).write_bytes(result.stdout)
    record = dict(label=label, argv=command, exit_code=result.returncode, seconds=time.perf_counter()-start,
                  log_sha256=hashlib.sha256(result.stdout).hexdigest(),
                  parse_jobs=data.count('parse once, render'),
                  inspector_jobs=data.count('Generate Inspector MetaUnit/inja author and Run projections:'))
    events.append(record)
    print(json.dumps(record), flush=True)
    assert (result.returncode == 0) == success, data[-4000:]
    return record, data

def compile(label, success=True):
    return run(label, ['cmake', '--build', str(build), '--target', 'all', '-j', '4', '--', '-k', '0'], success)

def outputs():
    return {str(path.relative_to(build)): (hashlib.sha256(path.read_bytes()).hexdigest(), path.stat().st_mtime_ns)
            for path in build.glob('inspector_gen/**/*')
            if path.is_file() and path.suffix in ('.cpp', '.hpp') and 'staging' not in path.parts}

def unchanged(label):
    before = outputs()
    record, data = compile(label)
    assert 'no work to do' in data and not record['parse_jobs'] and not record['inspector_jobs']
    assert outputs() == before

try:
    run('configure', config+['-DEC3_GENERATION_FLAG=1'])
    cold, _ = compile('cold')
    assert cold['inspector_jobs'] == 2
    # Same basename in different logical paths has two independently produced original MetaUnit sidecars.
    assert len(list(build.glob('inspector_ir/*_fields/*/Component.editor-ir.json'))) == 2
    assert len(outputs()) == 4
    executable = build/'bin/generation_consumer.exe' if os.name == 'nt' else build/'bin/generation_consumer'
    run('consumer', [str(executable)])
    unchanged('no-change')

    header = source/'include/a/Component.hpp'
    header.write_text(header.read_text().replace('max = 10', 'max = 11'), encoding='utf-8')
    field, _ = compile('field')
    assert field['parse_jobs'] > 0 and field['inspector_jobs'] > 0
    unchanged('after-field')

    common = source/'include/Common.hpp'
    common.write_text(common.read_text().replace('double', 'float'), encoding='utf-8')
    dependent, _ = compile('transitive-header')
    assert dependent['parse_jobs'] > 0 and dependent['inspector_jobs'] == 2

    template = codegen/'templates/component.template'
    template.write_text(template.read_text()+'\n// EC3 template dependency.\n', encoding='utf-8')
    rendered, _ = compile('template')
    assert rendered['parse_jobs'] == 0 and rendered['inspector_jobs'] == 2

    before = outputs()
    support = codegen/'support/InspectorControl.hpp'
    support.write_text(support.read_text()+'\n// EC3 support dependency.\n', encoding='utf-8')
    supported, _ = compile('support')
    assert supported['inspector_jobs'] == 2
    assert outputs() == before, 'Unchanged generated bytes must not be rewritten'

    run('flags-configure', config+['-DEC3_GENERATION_FLAG=2'])
    flags, _ = compile('flags')
    assert flags['parse_jobs'] > 0 and flags['inspector_jobs'] == 2
    unchanged('after-flags')

    (source/'include/Unrelated.hpp').write_text('// Not in any parser dependency.\n', encoding='utf-8')
    unchanged('unrelated-header')
    next(build.glob('inspector_ir/*_fields/*/Component.editor-ir.json')).unlink()
    missing_ir, _ = compile('missing-sidecar')
    assert missing_ir['parse_jobs'] > 0 and missing_ir['inspector_jobs'] > 0
    next(build.glob('inspector_gen/*_fields/*.cpp')).unlink()
    missing_cpp, _ = compile('missing-cpp')
    assert missing_cpp['inspector_jobs'] > 0
    next(build.glob('inspector_gen/*_fields/*.hpp')).unlink()
    missing_hpp, _ = compile('missing-hpp')
    assert missing_hpp['inspector_jobs'] > 0

    before, original = outputs(), template.read_bytes()
    template.write_bytes(original+b'\n{{ missing_key_for_failure }}\n')
    rejected, _ = compile('template-failure', False)
    assert outputs() == before and not list(build.glob('inspector_gen/*/inspector.complete'))
    template.write_bytes(original)
    compile('template-recovery')
    unchanged('final-no-change')
finally:
    (work/'events.json').write_text(json.dumps(events, indent=2)+'\n', encoding='utf-8')
